
WHENEVER OSERROR EXIT 1 ROLLBACK
WHENEVER SQLERROR EXIT 100 ROLLBACK

INSERT into WK_BATCH_TRACKER
(RUN_NO, STEP_NAME, START_TIME, END_TIME, RUN_STATUS, ACTIVE_FLAG)
values (to_char(sysdate,'YYYYMMDD'),'RDS HEARING',systimestamp,NULL,'R','Y');
COMMIT;

TRUNCATE TABLE  stg_rds_hearing_tbl reuse storage;

PROMPT "RDS HEARING: Insert into RDS hearing"

INSERT INTO stg_rds_hearing_tbl
		( 
			HEAR_NUMBER, 
			HEAR_HEARING_PROCESS_DTE, 
			HEAR_HEARING_PROCESS_TIM, 
			HEAR_HEARING_OFFICER, 
			HEAR_HEARING_DATE, 
			HEAR_HEARING_TIME , 
			HEAR_HEARING_CLERK,
			HEAR_HEARING_REQUIRED, 
			HEAR_HEARING_CASE_NO , 
			HEAR_TIMS_DATE_TIME,
			HEAR_RDS_DATE_TIME)
	select  
			TICKET_NUMBER, 
			HEAR_HEARING_PROCESS_DTE, 
			HEAR_HEARING_PROCESS_TIM, 
			HEARING_OFFICER, 
			HEAR_HEARING_DATE, 
			HEARING_TIME , 
			HEARING_CLERK,
			HEARING_REQUIRED, 
			HEAR_HEARING_CASE_NO , 
			tims_timestamp,
			SYSTIMESTAMP
from (	select RANK () over (partition by  TICKET_NUMBER,HEAR_HEARING_PROCESS_DTE,HEAR_HEARING_PROCESS_TIM, 
	HEARING_OFFICER  order by tims_timestamp desc, etl_seq_cd DESC) rec_no,
	TICKET_NUMBER,HEAR_HEARING_PROCESS_DTE,HEAR_HEARING_PROCESS_TIM, HEARING_OFFICER, 
	HEAR_HEARING_DATE, HEARING_TIME,HEARING_CLERK,HEARING_REQUIRED, HEAR_HEARING_CASE_NO, 
	tims_timestamp, SYSTIMESTAMP from  
	(SELECT
	    TICKET_NUMBER, 
        TO_DATE(CASE WHEN batch_date IN (0,9999999) THEN 1950365 ELSE 9999999-batch_date END,'YYYYDDD') HEAR_HEARING_PROCESS_DTE,
        24000 - BATCH_TIME HEAR_HEARING_PROCESS_TIM, 
		HEARING_OFFICER, 
		TO_DATE(CASE WHEN HEARING_DATE IN (0,9999999) THEN 1950365 ELSE HEARING_DATE END, 'YYYYDDD') HEAR_HEARING_DATE, 
		HEARING_TIME  , 
        	HEARING_CLERK , 
		HEARING_REQUIRED , 
		'?'  HEAR_HEARING_CASE_NO,
		tims_timestamp ,
		SYSTIMESTAMP
		etl_seq_cd
	from todays_tm2_ticket_hist 
	WHERE 
		trans_code LIKE '06_' AND TICKET_NUMBER > '0' 
		AND batch_date IS NOT NULL AND BATCH_TIME > 0 AND HEARING_OFFICER > ' '
		AND OP_STATUS IN ( 'INSERT', 'UPDATE', 'SQL COMPUPDATE','PK UPDATE')
AND tims_timestamp >= (select last_run_date from cfg_batch_run)
AND tims_timestamp < (select last_run_date + days_to_run from cfg_batch_run) 
	UNION 
	    SELECT 
			S.TICK_NUMBER TICKET_NUMBER, 
			TO_DATE(CASE WHEN NVL(HEARING_PROCESS_DTE,0) = 0 THEN 1950365 else HEARING_PROCESS_DTE END,'YYYYDDD') HEAR_HEARING_PROCESS_DTE,
            S.HEARING_PROCESS_TIM HEAR_HEARING_PROCESS_TIM, S.HEARING_OFFICER HEAR_HEARING_OFFICER, 
			TO_DATE(CASE WHEN NVL (HEARING_DATE,0) = 0 THEN 1950365 ELSE HEARING_DATE END, 'YYYYDDD') HEAR_HEARING_DATE, 
			S.HEARING_TIME HEAR_HEARING_TIME, 
			HEARING_CLERK HEAR_HEARING_CLERK, 
			S.HEARING_REQUIRED HEAR_HEARING_REQUIRED,
			S.CASE_NO HEAR_HEARING_CASE_NO,
			tims_timestamp HEAR_tims_date_time, 
			SYSTIMESTAMP
			etl_seq_cd
	    from todays_catchup_tick_segment2 S 
	    WHERE TICK_NUMBER > '0' 
		AND HEARING_PROCESS_DTE > '0' 
		AND HEARING_PROCESS_TIM > 0 
		AND HEARING_OFFICER > ' '
AND s.tims_timestamp >= (select last_run_date from cfg_batch_run)
AND s.tims_timestamp < (select last_run_date + days_to_run from cfg_batch_run) 
		AND OP_STATUS      IN ( 'INSERT', 'UPDATE', 'SQL COMPUPDATE','PK UPDATE')
	))
 where rec_no = 1;


COMMIT;

PROMPT "Delete-Insert RDS hearing"

delete from rds_hearing_tbl where ( HEAR_NUMBER,HEAR_HEARING_PROCESS_DTE,HEAR_HEARING_PROCESS_TIM, HEAR_HEARING_OFFICER) IN 
( select HEAR_NUMBER,HEAR_HEARING_PROCESS_DTE,HEAR_HEARING_PROCESS_TIM, HEAR_HEARING_OFFICER from stg_rds_hearing_tbl );

insert into rds_hearing_tbl
	( 
	HEAR_NUMBER, 
	HEAR_HEARING_PROCESS_DTE, 
	HEAR_HEARING_PROCESS_TIM, 
	HEAR_HEARING_OFFICER, 
	HEAR_HEARING_DATE, 
	HEAR_HEARING_TIME , 
	HEAR_HEARING_CLERK,
	HEAR_HEARING_REQUIRED, 
	HEAR_HEARING_CASE_NO , 
	HEAR_TIMS_DATE_TIME,
	HEAR_RDS_DATE_TIME
	)
select  
	HEAR_NUMBER, 
	HEAR_HEARING_PROCESS_DTE, 
	HEAR_HEARING_PROCESS_TIM, 
	HEAR_HEARING_OFFICER, 
	HEAR_HEARING_DATE, 
	HEAR_HEARING_TIME , 
	HEAR_HEARING_CLERK,
	HEAR_HEARING_REQUIRED, 
	HEAR_HEARING_CASE_NO , 
	HEAR_TIMS_DATE_TIME,
	HEAR_RDS_DATE_TIME
from stg_rds_hearing_tbl;

COMMIT;

PROMPT "Basic count check"
select count(1), count(HEAR_rds_date_time), count(HEAR_tims_date_time) from rds_hearing_tbl
where ( HEAR_NUMBER,HEAR_HEARING_PROCESS_DTE, HEAR_HEARING_PROCESS_TIM, HEAR_HEARING_OFFICER ) IN
( select  HEAR_NUMBER,HEAR_HEARING_PROCESS_DTE, HEAR_HEARING_PROCESS_TIM, HEAR_HEARING_OFFICER  from stg_rds_hearing_tbl);

PROMPT "Update status steps"
UPDATE todays_catchup_tick_segment2 
SET ETL_STATUS_CD = 20 WHERE ETL_STATUS_CD = 19;
COMMIT;

UPDATE todays_tm2_ticket_hist 
SET ETL_STATUS_CD = 20 WHERE ETL_STATUS_CD = 15 and trans_code LIKE '06_' AND TICKET_NUMBER > '0' AND HEARING_OFFICER > ' ' AND NVL(batch_date, 0) <> 0;
COMMIT;

UPDATE stg_columbus_dtl.TM2_TICKET_HISTORY@stg_dblink 
SET ETL_STATUS_CD = 20 WHERE ETL_STATUS_CD = 15 and trans_code LIKE '06_' AND TICKET_NUMBER > '0' AND HEARING_OFFICER > ' ' AND NVL(batch_date, 0) <> 0;
COMMIT;

UPDATE stg_columbus_dtl.TICK_SEGMENT@stg_dblink
SET ETL_STATUS_CD = 65 WHERE ETL_STATUS_CD = 15 and tick_number in (select HEAR_NUMBER from stg_rds_hearing_tbl);
COMMIT;

update WK_BATCH_TRACKER set end_time=systimestamp, run_status='Y' where STEP_NAME='RDS HEARING';
COMMIT;

EXIT;

