
WHENEVER OSERROR EXIT 1 ROLLBACK
WHENEVER SQLERROR EXIT 100 ROLLBACK

INSERT into WK_BATCH_TRACKER
(RUN_NO, STEP_NAME, START_TIME, END_TIME, RUN_STATUS, ACTIVE_FLAG)
values (to_char(sysdate,'YYYYMMDD'),'RDS SEIZURE',systimestamp,NULL,'R','Y');
COMMIT;

TRUNCATE TABLE DW_SEIZURE_TMP_TBL;

PROMPT RDS SEIZURE: Insert into DW_SEIZURE_TMP_TBL

INSERT INTO DW_SEIZURE_TMP_TBL
        (ISN, SEIZ_STATE_PLATE_TYPE, SEIZ_RECORD_NUMBER, OP_STATUS, TIMS_TIMESTAMP, ETL_SEQ_CD, Source_ROWID)
        SELECT S.ISN, SEIZ_STATE_PLATE_TYPE, S.SEIZ_RECORD_NUMBER,
        S.OP_STATUS, S.TIMS_TIMESTAMP, S.ETL_SEQ_CD, S.Source_ROWID
        FROM ( SELECT RANK() OVER (PARTITION BY TRIM(S.SEIZ_PLATE_TYPE||S.SEIZ_STATE_PLATE), S.SEIZ_RECORD_NUMBER
                             ORDER BY TRIM(S.SEIZ_PLATE_TYPE||S.SEIZ_STATE_PLATE), S.SEIZ_RECORD_NUMBER, S.ISN, S.etl_status_cd, S.ETL_SEQ_CD ASC, S.TIMS_TIMESTAMP ASC) rec_num,
                  TRIM(S.SEIZ_PLATE_TYPE||S.SEIZ_STATE_PLATE) as SEIZ_STATE_PLATE_TYPE, S.SEIZ_RECORD_NUMBER, S.ISN, S.OP_STATUS, S.etl_status_cd, S.TIMS_TIMESTAMP, S.ETL_SEQ_CD, S.ROWID AS Source_ROWID
               FROM STG_COLUMBUS_DTL.TM2_SEIZURE_FILE@stg_dblink S
               WHERE LENGTH(TRIM(S.SEIZ_RECORD_NUMBER)) > 0 AND LENGTH(TRIM(S.SEIZ_STATE_PLATE)) > 0
                   AND S.etl_status_cd = 10
                   AND S.OP_STATUS IN ( 'INSERT', 'UPDATE', 'SQL COMPUPDATE')
       AND s.tims_timestamp >= (select last_run_date from cfg_batch_run)
    AND s.tims_timestamp < (select last_run_date + days_to_run from cfg_batch_run)                   
             ) S WHERE REC_NUM = 1 ;

COMMIT;

PROMPT "Delete-Insert DW_SEIZURE_TMP_TBL"

DELETE FROM RDS_SEIZURE_TBL D
        WHERE EXISTS
        ( SELECT 1
          FROM DW_SEIZURE_TMP_TBL T
          WHERE D.SEIZ_STATE_PLATE_TYPE = T.SEIZ_STATE_PLATE_TYPE
          AND D.SEIZ_RECORD_NUMBER = T.SEIZ_RECORD_NUMBER
          AND ( T.OP_STATUS = 'INSERT' OR T.OP_STATUS = 'UPDATE' OR T.OP_STATUS = 'SQL COMPUPDATE'));

INSERT INTO RDS_SEIZURE_TBL
        (   SEIZ_STATE_PLATE_TYPE, SEIZ_RECORD_NUMBER, SEIZ_OPEN_CLOSE, SEIZ_STATUS_CODE,
            SEIZ_AUTH_LOC, SEIZ_OP_ID, SEIZ_AUTH_EXEC_NUM, SEIZ_AUTH_PVB_REF,
            SEIZ_AUTH_LOC_CODE, SEIZ_MOVE_TO_LOC, SEIZ_AUTH_COLOR, SEIZ_AUTH_MAKE,
            SEIZ_AUTH_VIN, SEIZ_AUTH_AMOUNT, SEIZ_AUTH_TOT_INTRST, SEIZ_AUTH_TICK_CT,
            SEIZ_COMMENTS, SEIZ_COLL_TICKET_CNT, SEIZ_COLL_TICKET_AMT, SEIZ_COLL_TICKET_INTRST,
            SEIZ_COLL_BOOT_FEE, SEIZ_COLL_TOW_FEE, SEIZ_COLL_STORE_FEE, SEIZ_VEHICLE_YEAR,
            SEIZ_BOOT_AUTH_DATE, SEIZ_BOOT_AUTH_TIME, SEIZ_BOOT_AUTH_CREW, SEIZ_BOOT_AUTH_OP_ID,
            SEIZ_BOOT_AUTH_OPTION, SEIZ_BOOT_DISP_DATE, SEIZ_BOOT_DISP_TIME, SEIZ_BOOT_DISP_OP_ID,
            SEIZ_BOOT_CONF_DATE, SEIZ_BOOT_CONF_TIME, SEIZ_BOOT_CONF_CREW, SEIZ_BOOT_CONF_OP_ID,
            SEIZ_BOOT_CONF_BOOT_NUM, SEIZ_BOOT_CONF_OPTION, SEIZ_TOW_AUTH_DATE, SEIZ_TOW_AUTH_TIME,
            SEIZ_TOW_AUTH_CREW, SEIZ_TOW_AUTH_OP_ID, SEIZ_TOW_AUTH_REASON, SEIZ_TOW_AUTH_OPTION,
            SEIZ_TOW_DISP_DATE, SEIZ_TOW_DISP_TIME, SEIZ_TOW_DISP_OP_ID, SEIZ_TOW_CONF_DATE,
            SEIZ_TOW_CONF_TIME, SEIZ_TOW_CONF_CREW, SEIZ_TOW_CONF_OP_ID, SEIZ_TOW_CONF_LOT,
            SEIZ_TOW_CONF_LOT_LEVEL, SEIZ_TOW_CONF_LOT_ROW, SEIZ_TOW_CONF_LOT_SPACE, SEIZ_TOW_CONF_OPTION,
            SEIZ_BOOT_RLSE_AUTH_DATE, SEIZ_BOOT_RLSE_AUTH_TIME, SEIZ_BOOT_RLSE_AUTH_CREW, SEIZ_BOOT_RLSE_AUTH_OP_ID,
            SEIZ_BOOT_RLSE_REASON, SEIZ_BOOT_RLSE_AUTH_OPTION, SEIZ_BOOT_RLSE_DISP_DATE, SEIZ_BOOT_RLSE_DISP_TIME,
            SEIZ_BOOT_RLSE_DISP_OP_ID, SEIZ_BOOT_RLSE_CONF_DATE, SEIZ_BOOT_RLSE_CONF_TIME, SEIZ_BOOT_RLSE_CONF_CREW,
            SEIZ_BOOT_RLSE_CONF_OP_ID, SEIZ_BOOT_RLSE_CONF_OPTION, SEIZ_TOW_RLSE_AUTH_DATE, SEIZ_TOW_RLSE_AUTH_TIME,
            SEIZ_TOW_RLSE_AUTH_CREW, SEIZ_TOW_RLSE_AUTH_OP_ID, SEIZ_TOW_RLSE_REASON, SEIZ_TOW_RLSE_AUTH_OPTION,
            SEIZ_TOW_RLSE_CONF_DATE, SEIZ_TOW_RLSE_CONF_TIME, SEIZ_TOW_RLSE_CONF_CREW, SEIZ_TOW_RLSE_CONF_OP_ID,
            SEIZ_TOW_RLSE_CONF_OPTION, SEIZ_REDEEM_NAME, SEIZ_REDEEM_ADD_1, SEIZ_REDEEM_ADD_2,
            SEIZ_REDEEM_CITY, SEIZ_REDEEM_STATE, SEIZ_TRANS_ID, SEIZ_REDEEM_ID_TYPE,
            SEIZ_REDEEM_ID_NUM, SEIZ_LIEN_NAME, SEIZ_LIEN_ADD_1, SEIZ_LIEN_ADD_2,
            SEIZ_LIEN_CITY, SEIZ_LIEN_STATE, SEIZ_LIEN_ZIP, SEIZ_NOTICE_DMV,
            SEIZ_NOTICE_LIEN, SEIZ_NOTICE_OWNER_1, SEIZ_NOTICE_OWNER_2, SEIZ_NOTICE_OWNER_3,
            SEIZ_AUCTION_ELIG_DATE, SEIZ_AUCTION_STATUS, SEIZ_AUCTION_ON_DATE, SEIZ_AUCTION_FOR_DOLL,
            SEIZ_AUCTION_DOLL_REM, SEIZ_ASSOC_PLT_DOLLARS, SEIZ_ASSOC_PLT_PAID, SEIZ_AGENT_EFF_DATE,
            SEIZ_AGENT_DATE_PAID, SEIZ_VEH_TYPE, SEIZ_TOWO_VEH_VIN, SEIZ_TOWO_VEH_TRANSID,
            SEIZ_TOWO_VEH_MODEL, SEIZ_TOWO_VEH_DESC, SEIZ_TOWO_VEH_TICKET, SEIZ_TOWO_VEH_VIOLATION,
            SEIZ_TOWO_VEH_DISTRICT, SEIZ_TOWO_VEH_OPERABLE, SEIZ_TOWO_VEH_TOW_REASON, SEIZ_TOWO_VEH_COMMENTS,
            SEIZ_TOWO_VEH_YR, SEIZ_TOWO_VEH_OFFICER, SEIZ_TOWO_VEH_SQUAD, SEIZ_TOWO_INV_CREATDTE,
            SEIZ_TOWO_VEH_MISC_DATA, SEIZ_TOWO_VEH_UPDATE_DATA, SEIZ_TOWO_VEH_CHGDTE, SEIZ_TOWO_VEH_COLOR,
            SEIZ_TOWO_VEH_CHGTYPE, SEIZ_TOWO_NXT_ACT_DATE, SEIZ_TOWO_NXT_ACT_TYPE, SEIZ_TOWO_VEH_CHGTME,
            SEIZ_TOWO_VEH_STOLEN_ID, SEZI_TOWO_VEH_MISC_DATA, SEIZ_TOWO_CALL_DATE, SEIZ_TOWO_CALL_TIME,
            SEIZ_TOWO_CALL_OP_ID, SEIZ_TOWO_CALL_NAME, SEIZ_TOWO_CALL_ADDR1, SEIZ_TOWO_CALL_ADDR2,
            SEIZ_TOWO_CALL_CITY, SEIZ_TOWO_CALL_STATE, SEIZ_TOWO_CALL_ZIP, SEIZ_TOWO_CALL_PHONE,
            SEIZ_TOWO_CALL_MISC1, SEIZ_TOWO_CALL_MISC2, SEIZ_TOWO_SITE_DATE, SEIZ_TOWO_SITE_TIME,
            SEIZ_TOWO_SITE_OP_ID, SEIZ_TOWO_SITE_OPTION, SEIZ_TOWO_OWNR_LAST, SEIZ_TOWO_OWNR_FIRST,
            SEIZ_TOWO_OWNR_NAME, SEIZ_TOWO_OWNR_ADDR1, SEIZ_TOWO_OWNR_ADDR2, SEIZ_TOWO_OWNR_CITY,
            SEIZ_TOWO_OWNR_STATE, SEIZ_TOWO_OWNR_ZIP, SEIZ_TOWO_OWNR_ZIP_RT, SEIZ_TOWO_VIN_NAME,
            SEIZ_TOWO_VIN_ADDR1, SEIZ_TOWO_VIN_ADDR2, SEIZ_TOWO_VIN_CITY, SEIZ_TOWO_VIN_STATE,
            SEIZ_TOWO_VIN_ZIP, SEIZ_TOWO_VIN_ZIP_RT, SEIZ_TOWO_LEGL_LAST, SEIZ_TOWO_LEGL_FIRST,
            SEIZ_TOWO_LEGL_NAME, SEIZ_TOWO_LEGL_ADDR1, SEIZ_TOWO_LEGL_ADDR2, SEIZ_TOWO_LEGL_CITY,
            SEIZ_TOWO_LEGL_STATE, SEIZ_TOWO_LEGL_ZIP, SEIZ_TOWO_LEGL_ZIP_RT, SEIZ_TOWO_REG_CONF_DATE,
            SEIZ_TOWO_REG_CONF_TIME, SEIZ_TOWO_REG_CONF_OPID, SEIZ_TOWO_STOLEN, SEIZ_TOWO_ADDR_SOURCE,
            SEIZ_TOWO_MISC_DATE1, SEIZ_TOWO_MISC_DATA, SEIZ_TOWO_ADDR_UPDATE_DATA, SEIZ_TOWO_MISC_FILL1,
            SEIZ_TOWO_MISC_FILL2, SEIZ_TOWO_ADDR_LEG2_NAME, SEIZ_TOWO_LEG2_LAST, SEIZ_TOWO_LEG2_FIRST,
            SEIZ_TOWO_LEG2_ADDR1, SEIZ_TOWO_LEG2_ADDR2, SEIZ_TOWO_LEG2_CITY, SEIZ_TOWO_LEG2_STATE,
            SEIZ_TOWO_LEG2_ZIP, SEIZ_TOWO_LEG2_ZIP_RT, SEIZ_TOWO_RELS_REASON, SEIZ_TOWO_RELS_INVOICE,
            SEIZ_TOWO_RELS_DISP_DTE, SEIZ_TOWO_RELS_MISC, SEIZ_TOWO_FEE_ACCESS, SEIZ_TOWO_RELS_MISC_DATE1,
            SEIZ_TOWO_RELS_MISC_DATE2, SEIZ_TOWO_NOTICE_TYPE, SEIZ_TOWO_NOTICE_DATE, SEIZ_TOWO_NOTICE_PROC_DATE,
            SEIZ_TOWO_NOTICE_MISC_DATE, SEIZ_TOWO_NOTICE_MISC_COMM,
            seiz_tims_date_time, SEIZ_RDS_DATE_TIME )
          SELECT
            TRIM(S.SEIZ_PLATE_TYPE||S.SEIZ_STATE_PLATE), S.SEIZ_RECORD_NUMBER, SEIZ_OPEN_CLOSE, SEIZ_STATUS_CODE,
            SEIZ_AUTH_LOC, SEIZ_OP_ID, SEIZ_AUTH_EXEC_NUM, SEIZ_AUTH_PVB_REF,
            SEIZ_AUTH_LOC_CODE, SEIZ_MOVE_TO_LOC, SEIZ_AUTH_COLOR, SEIZ_AUTH_MAKE,
            SEIZ_AUTH_VIN, SEIZ_AUTH_AMOUNT, SEIZ_AUTH_TOT_INTRST, SEIZ_AUTH_TICK_CT,
            SEIZ_COMMENTS, SEIZ_COLL_TICKET_CNT, SEIZ_COLL_TICKET_AMT, SEIZ_COLL_TICKET_INTRST,
            SEIZ_COLL_BOOT_FEE, SEIZ_COLL_TOW_FEE, SEIZ_COLL_STORE_FEE, SEIZ_VEHICLE_YEAR,
            TO_DATE(CASE WHEN S.SEIZ_BOOT_AUTH_DATE IN (0,9999999) THEN 1950365 ELSE S.SEIZ_BOOT_AUTH_DATE END,'YYYYDDD') AS SEIZ_BOOT_AUTH_DATE,
            SEIZ_BOOT_AUTH_TIME, SEIZ_BOOT_AUTH_CREW, SEIZ_BOOT_AUTH_OP_ID,
            SEIZ_BOOT_AUTH_OPTION,
            TO_DATE(CASE WHEN S.SEIZ_BOOT_DISP_DATE IN (0,9999999) THEN 1950365 ELSE S.SEIZ_BOOT_DISP_DATE END,'YYYYDDD') AS SEIZ_BOOT_DISP_DATE,
            SEIZ_BOOT_DISP_TIME, SEIZ_BOOT_DISP_OP_ID,
            TO_DATE(CASE WHEN S.SEIZ_BOOT_CONF_DATE IN (0,9999999) THEN 1950365 ELSE S.SEIZ_BOOT_CONF_DATE END,'YYYYDDD') AS SEIZ_BOOT_CONF_DATE,
            SEIZ_BOOT_CONF_TIME, SEIZ_BOOT_CONF_CREW, SEIZ_BOOT_CONF_OP_ID,
            SEIZ_BOOT_CONF_BOOT_NUM, SEIZ_BOOT_CONF_OPTION,
            TO_DATE(CASE WHEN S.SEIZ_TOW_AUTH_DATE IN (0,9999999) THEN 1950365 ELSE S.SEIZ_TOW_AUTH_DATE END,'YYYYDDD') AS SEIZ_TOW_AUTH_DATE,
            SEIZ_TOW_AUTH_TIME,
            SEIZ_TOW_AUTH_CREW, SEIZ_TOW_AUTH_OP_ID, SEIZ_TOW_AUTH_REASON, SEIZ_TOW_AUTH_OPTION,
            TO_DATE(CASE WHEN S.SEIZ_TOW_DISP_DATE IN (0,9999999) THEN 1950365 ELSE S.SEIZ_TOW_DISP_DATE END,'YYYYDDD') AS SEIZ_TOW_DISP_DATE,
            SEIZ_TOW_DISP_TIME, SEIZ_TOW_DISP_OP_ID,
            TO_DATE(CASE WHEN S.SEIZ_TOW_CONF_DATE IN (0,9999999) THEN 1950365 ELSE S.SEIZ_TOW_CONF_DATE END,'YYYYDDD') AS SEIZ_TOW_CONF_DATE,
            SEIZ_TOW_CONF_TIME, SEIZ_TOW_CONF_CREW, SEIZ_TOW_CONF_OP_ID, SEIZ_TOW_CONF_LOT,
            SEIZ_TOW_CONF_LOT_LEVEL, SEIZ_TOW_CONF_LOT_ROW, SEIZ_TOW_CONF_LOT_SPACE, SEIZ_TOW_CONF_OPTION,
            TO_DATE(CASE WHEN S.SEIZ_BOOT_RLSE_AUTH_DATE IN (0,9999999) THEN 1950365 ELSE S.SEIZ_BOOT_RLSE_AUTH_DATE END,'YYYYDDD') AS SEIZ_BOOT_RLSE_AUTH_DATE,
            SEIZ_BOOT_RLSE_AUTH_TIME, SEIZ_BOOT_RLSE_AUTH_CREW, SEIZ_BOOT_RLSE_AUTH_OP_ID,
            SEIZ_BOOT_RLSE_REASON, SEIZ_BOOT_RLSE_AUTH_OPTION,
            TO_DATE(CASE WHEN S.SEIZ_BOOT_RLSE_DISP_DATE IN (0,9999999) THEN 1950365 ELSE S.SEIZ_BOOT_RLSE_DISP_DATE END,'YYYYDDD') AS SEIZ_BOOT_RLSE_DISP_DATE,
            SEIZ_BOOT_RLSE_DISP_TIME,
            SEIZ_BOOT_RLSE_DISP_OP_ID,
            TO_DATE(CASE WHEN S.SEIZ_BOOT_RLSE_CONF_DATE IN (0,9999999) THEN 1950365 ELSE  S.SEIZ_BOOT_RLSE_CONF_DATE END,'YYYYDDD') AS SEIZ_BOOT_RLSE_CONF_DATE,
            SEIZ_BOOT_RLSE_CONF_TIME, SEIZ_BOOT_RLSE_CONF_CREW,
            SEIZ_BOOT_RLSE_CONF_OP_ID, SEIZ_BOOT_RLSE_CONF_OPTION,
            TO_DATE(CASE WHEN S.SEIZ_TOW_RLSE_AUTH_DATE IN (0,9999999) THEN 1950365 ELSE  S.SEIZ_TOW_RLSE_AUTH_DATE END,'YYYYDDD') AS SEIZ_TOW_RLSE_AUTH_DATE,
            SEIZ_TOW_RLSE_AUTH_TIME,
            SEIZ_TOW_RLSE_AUTH_CREW, SEIZ_TOW_RLSE_AUTH_OP_ID, SEIZ_TOW_RLSE_REASON, SEIZ_TOW_RLSE_AUTH_OPTION,
            TO_DATE(CASE WHEN S.SEIZ_TOW_RLSE_CONF_DATE IN (0,9999999) THEN 1950365 ELSE  S.SEIZ_TOW_RLSE_CONF_DATE END,'YYYYDDD') AS SEIZ_TOW_RLSE_CONF_DATE,
            SEIZ_TOW_RLSE_CONF_TIME, SEIZ_TOW_RLSE_CONF_CREW, SEIZ_TOW_RLSE_CONF_OP_ID,
            SEIZ_TOW_RLSE_CONF_OPTION, SEIZ_REDEEM_NAME, SEIZ_REDEEM_ADD_1, SEIZ_REDEEM_ADD_2,
            SEIZ_REDEEM_CITY, SEIZ_REDEEM_STATE, SEIZ_TRANS_ID, SEIZ_REDEEM_ID_TYPE,
            SEIZ_REDEEM_ID_NUM, SEIZ_LIEN_NAME, SEIZ_LIEN_ADD_1, SEIZ_LIEN_ADD_2,
            SEIZ_LIEN_CITY, SEIZ_LIEN_STATE, SEIZ_LIEN_ZIP, SEIZ_NOTICE_DMV,
            SEIZ_NOTICE_LIEN, SEIZ_NOTICE_OWNER_1, SEIZ_NOTICE_OWNER_2, SEIZ_NOTICE_OWNER_3,
            TO_DATE(CASE WHEN S.SEIZ_AUCTION_ELIG_DATE IN (0,9999999) THEN 1950365 ELSE  S.SEIZ_AUCTION_ELIG_DATE END,'YYYYDDD') AS SEIZ_AUCTION_ELIG_DATE,
            SEIZ_AUCTION_STATUS,
            TO_DATE(CASE WHEN S.SEIZ_AUCTION_ON_DATE IN (0,9999999) THEN 1950365 ELSE  S.SEIZ_AUCTION_ON_DATE END,'YYYYDDD') AS SEIZ_AUCTION_ON_DATE,
            SEIZ_AUCTION_FOR_DOLL,
            SEIZ_AUCTION_DOLL_REM, SEIZ_ASSOC_PLT_DOLLARS, SEIZ_ASSOC_PLT_PAID,
            TO_DATE(CASE WHEN S.SEIZ_AGENT_EFF_DATE IN (0,9999999) THEN 1950365 ELSE  S.SEIZ_AGENT_EFF_DATE END,'YYYYDDD') AS SEIZ_AGENT_EFF_DATE,
            SEIZ_AGENT_DATE_PAID, SEIZ_VEH_TYPE, SEIZ_TOWO_VEH_VIN, SEIZ_TOWO_VEH_TRANSID,
            TRIM(seiz_towo_veh_model) as seiz_towo_veh_model, SEIZ_TOWO_VEH_DESC, SEIZ_TOWO_VEH_TICKET, SEIZ_TOWO_VEH_VIOLATION,
            SEIZ_TOWO_VEH_DISTRICT, SEIZ_TOWO_VEH_OPERABLE, SEIZ_TOWO_VEH_TOW_REASON, SEIZ_TOWO_VEH_COMMENTS,
            SEIZ_TOWO_VEH_YR, SEIZ_TOWO_VEH_OFFICER, SEIZ_TOWO_VEH_SQUAD,
            TO_DATE(CASE WHEN S.SEIZ_TOWO_INV_CREATDTE IN (0,9999999) THEN 1950365 ELSE 9999999- S.SEIZ_TOWO_INV_CREATDTE END,'YYYYDDD') AS SEIZ_TOWO_INV_CREATDTE,
            SEIZ_TOWO_VEH_MISC_DATA, SEIZ_TOWO_VEH_UPDATE_DATA,
            TO_DATE(CASE WHEN S.SEIZ_TOWO_VEH_CHGDTE IN (0,9999999) THEN 1950365 ELSE  S.SEIZ_TOWO_VEH_CHGDTE END,'YYYYDDD') AS SEIZ_TOWO_VEH_CHGDTE,
            SEIZ_TOWO_VEH_COLOR,
            SEIZ_TOWO_VEH_CHGTYPE,
            TO_DATE(CASE WHEN S.SEIZ_TOWO_NXT_ACT_DATE IN (0,9999999) THEN 1950365 ELSE  S.SEIZ_TOWO_NXT_ACT_DATE END,'YYYYDDD') AS SEIZ_TOWO_NXT_ACT_DATE,
            SEIZ_TOWO_NXT_ACT_TYPE, SEIZ_TOWO_VEH_CHGTME,
            SEIZ_TOWO_VEH_STOLEN_ID, SEZI_TOWO_VEH_MISC_DATA,
            TO_DATE(CASE WHEN S.SEIZ_TOWO_CALL_DATE IN (0,9999999) THEN 1950365 ELSE  S.SEIZ_TOWO_CALL_DATE END,'YYYYDDD') AS SEIZ_TOWO_CALL_DATE,
            SEIZ_TOWO_CALL_TIME,
            SEIZ_TOWO_CALL_OP_ID, SEIZ_TOWO_CALL_NAME, SEIZ_TOWO_CALL_ADDR1, SEIZ_TOWO_CALL_ADDR2,
            SEIZ_TOWO_CALL_CITY, SEIZ_TOWO_CALL_STATE, SEIZ_TOWO_CALL_ZIP, SEIZ_TOWO_CALL_PHONE,
            SEIZ_TOWO_CALL_MISC1, SEIZ_TOWO_CALL_MISC2,
            TO_DATE(CASE WHEN S.SEIZ_TOWO_SITE_DATE IN (0,9999999) THEN 1950365 ELSE  S.SEIZ_TOWO_SITE_DATE END,'YYYYDDD') AS SEIZ_TOWO_SITE_DATE,
            SEIZ_TOWO_SITE_TIME,
            SEIZ_TOWO_SITE_OP_ID, SEIZ_TOWO_SITE_OPTION, SEIZ_TOWO_OWNR_LAST, SEIZ_TOWO_OWNR_FIRST,
            SEIZ_TOWO_OWNR_NAME, SEIZ_TOWO_OWNR_ADDR1, SEIZ_TOWO_OWNR_ADDR2, SEIZ_TOWO_OWNR_CITY,
            SEIZ_TOWO_OWNR_STATE, SEIZ_TOWO_OWNR_ZIP, SEIZ_TOWO_OWNR_ZIP_RT, SEIZ_TOWO_VIN_NAME,
            SEIZ_TOWO_VIN_ADDR1, SEIZ_TOWO_VIN_ADDR2, SEIZ_TOWO_VIN_CITY, SEIZ_TOWO_VIN_STATE,
            SEIZ_TOWO_VIN_ZIP, SEIZ_TOWO_VIN_ZIP_RT, SEIZ_TOWO_LEGL_LAST, SEIZ_TOWO_LEGL_FIRST,
            SEIZ_TOWO_LEGL_NAME, SEIZ_TOWO_LEGL_ADDR1, SEIZ_TOWO_LEGL_ADDR2, SEIZ_TOWO_LEGL_CITY,
            SEIZ_TOWO_LEGL_STATE, SEIZ_TOWO_LEGL_ZIP, SEIZ_TOWO_LEGL_ZIP_RT,
            TO_DATE(CASE WHEN S.SEIZ_TOWO_REG_CONF_DATE IN (0,9999999) THEN 1950365 ELSE S.SEIZ_TOWO_REG_CONF_DATE END,'YYYYDDD') AS SEIZ_TOWO_REG_CONF_DATE,
            SEIZ_TOWO_REG_CONF_TIME, SEIZ_TOWO_REG_CONF_OPID, SEIZ_TOWO_STOLEN, SEIZ_TOWO_ADDR_SOURCE,
            TO_DATE(CASE WHEN S.SEIZ_TOWO_MISC_DATE1 IN (0,9999999) THEN 1950365 ELSE  S.SEIZ_TOWO_MISC_DATE1 END,'YYYYDDD') AS SEIZ_TOWO_MISC_DATE1,
            SEIZ_TOWO_MISC_DATA, SEIZ_TOWO_ADDR_UPDATE_DATA, SEIZ_TOWO_MISC_FILL1,
            SEIZ_TOWO_MISC_FILL2, SEIZ_TOWO_ADDR_LEG2_NAME, SEIZ_TOWO_LEG2_LAST, SEIZ_TOWO_LEG2_FIRST,
            SEIZ_TOWO_LEG2_ADDR1, SEIZ_TOWO_LEG2_ADDR2, SEIZ_TOWO_LEG2_CITY, SEIZ_TOWO_LEG2_STATE,
            SEIZ_TOWO_LEG2_ZIP, SEIZ_TOWO_LEG2_ZIP_RT, SEIZ_TOWO_RELS_REASON, SEIZ_TOWO_RELS_INVOICE,
            TO_DATE(CASE WHEN S.SEIZ_TOWO_RELS_DISP_DTE IN (0,9999999) THEN 1950365 ELSE S.SEIZ_TOWO_RELS_DISP_DTE END,'YYYYDDD') AS SEIZ_TOWO_RELS_DISP_DTE,
            SEIZ_TOWO_RELS_MISC, SEIZ_TOWO_FEE_ACCESS,
            TO_DATE(CASE WHEN S.SEIZ_TOWO_RELS_MISC_DATE1 IN (0,9999999) THEN 1950365 ELSE S.SEIZ_TOWO_RELS_MISC_DATE1 END,'YYYYDDD') AS SEIZ_TOWO_RELS_MISC_DATE1,
            TO_DATE(CASE WHEN S.SEIZ_TOWO_RELS_MISC_DATE2 IN (0,9999999) THEN 1950365 ELSE S.SEIZ_TOWO_RELS_MISC_DATE2 END,'YYYYDDD') AS SEIZ_TOWO_RELS_MISC_DATE2,
            S1.TYPE AS SEIZ_TOWO_NOTICE_TYPE,
            TO_DATE(CASE WHEN S1.SEIZ_TOWO_NOTICE_DATE IN (0,9999999) THEN 1950365 ELSE S1.SEIZ_TOWO_NOTICE_DATE END,'YYYYDDD') AS SEIZ_TOWO_NOTICE_DATE,
            TO_DATE(CASE WHEN S1.PROC_DATE IN (0,9999999) THEN 1950365 ELSE S1.PROC_DATE END,'YYYYDDD') AS SEIZ_TOWO_NOTICE_PROC_DATE,
            TO_DATE(CASE WHEN S1.MISC_DATE IN (0,9999999) THEN 1950365 ELSE S1.MISC_DATE END,'YYYYDDD') AS SEIZ_TOWO_NOTICE_MISC_DATE,
            S1.MISC_COMM AS SEIZ_TOWO_NOTICE_MISC_COMM,
            t.tims_timestamp, systimestamp 
          FROM (STG_COLUMBUS_DTL.TM2_SEIZURE_FILE@stg_dblink S JOIN DW_SEIZURE_TMP_TBL T ON S.ROWID = T.SOURCE_ROWID)
             LEFT OUTER JOIN 
             (select isn,max(idx),max(TYPE) as TYPE,max(SEIZ_TOWO_NOTICE_DATE) as SEIZ_TOWO_NOTICE_DATE,
             max(PROC_DATE)as PROC_DATE,max(MISC_DATE) as MISC_DATE,max(MISC_COMM) as MISC_COMM 
             from STG_COLUMBUS_DTL.SEIZ_TOWO_NOTICE_DATA@stg_dblink group by isn) S1
            ON S.ISN = S1.ISN;

COMMIT;

UPDATE STG_COLUMBUS_DTL.TM2_SEIZURE_FILE@stg_dblink S
          SET ETL_STATUS_CD = 20
          WHERE EXISTS (SELECT 1
                        FROM DW_SEIZURE_TMP_TBL T
                        where S.ROWID = T.SOURCE_ROWID
                        );

COMMIT;      

update WK_BATCH_TRACKER set end_time=systimestamp, run_status='Y' where STEP_NAME='RDS SEIZURE';
COMMIT;

EXIT;

