-- Please make sure only one instance running this process 

WHENEVER OSERROR EXIT 1 ROLLBACK
WHENEVER SQLERROR EXIT 100 ROLLBACK

--SET TIMING ON

SET SERVEROUTPUT ON SIZE 999999
DECLARE
v_total_steps NUMBER := 13;
v_run_steps NUMBER := 0;
bad_previous_run EXCEPTION;

BEGIN

    SELECT COUNT(1) INTO v_run_steps 
    FROM WK_BATCH_TRACKER WHERE run_status = 'Y';
  
    IF (v_run_steps <> v_total_steps) THEN 
      RAISE bad_previous_run;
    END IF;
    dbms_output.put_line('Check for the previous run was found to be OK. Proceeding...');

    --Previous run was OK, so set the date for the NEW run
    UPDATE cfg_batch_run SET last_run_date=last_run_date + days_to_run;

    --Delete this row if we already had any runs today. 
    DELETE FROM dw_load_status_tbl_new a
    WHERE A.dw_load_start_date_id=to_number( to_char(sysdate,'YYYYMMDD') );

    COMMIT;

  EXCEPTION
    WHEN bad_previous_run THEN
      RAISE_APPLICATION_ERROR(-20003,'Critical Alert! Previous run not successful');
    WHEN OTHERS THEN
      dbms_output.put_line('Critical Alert! Unknown error');
      RAISE;
END;
/


TRUNCATE TABLE WK_BATCH_TRACKER;

INSERT into WK_BATCH_TRACKER
(RUN_NO, STEP_NAME, START_TIME, END_TIME, RUN_STATUS, ACTIVE_FLAG)
values (to_char(sysdate,'YYYYMMDD'),'RDS RP',systimestamp,NULL,'R','Y');
COMMIT;

select LAST_RUN_DATE,days_to_run from cfg_batch_run;

truncate table stg_tm2_ticket_summary reuse storage;
truncate table stg_rds_rp_tbl;

update stg_columbus_dtl.TM2_TICKET_SUMMARY@stg_dblink ts
set ts.etl_status_cd = 15 where ts.etl_status_cd=10
AND ts.op_status IN ('INSERT','DELETE','UPDATE','SQL COMPUPDATE')
     AND tims_timestamp >= (select last_run_date from cfg_batch_run)
     AND tims_timestamp < (select last_run_date + days_to_run from cfg_batch_run);

commit;

UPDATE stg_columbus_dtl.tick_segment@stg_dblink s set s.ETL_STATUS_CD=15
where s.tick_number >= '0' AND s.ETL_STATUS_CD=10
   AND tims_timestamp >= (select last_run_date from cfg_batch_run)
   AND tims_timestamp < (select last_run_date + days_to_run from cfg_batch_run);
      
COMMIT;

update stg_columbus_dtl.TM2_TICKET_HISTORY@stg_dblink ts
set ts.etl_status_cd = 15 where ts.etl_status_cd=10
and TICKET_NUMBER > '0' AND ts.op_status IN ('INSERT','DELETE','UPDATE','SQL COMPUPDATE')
   AND tims_timestamp >= (select last_run_date from cfg_batch_run)
   AND tims_timestamp < (select last_run_date + days_to_run from cfg_batch_run);

commit;

--****SAVE/REFERENCE purposes

truncate table stg_tm2_ticket_summary;

insert into todays_TM2_TICKET_SUMMARY (ISN,SUMM_ENTITY_NUMBER,SUMM_REC_NUMBER,SUMM_TICKET_TYPE,SUMM_STATE_DRIVER_LIC,SUMM_DRIVER_LIC_CLASS,SUMM_HOME_IND,SUMM_SAVE_STATE_PLATE,SUMM_STATE_PLATE,SUMM_PLATE_TYPE,SUMM_PLATE_TYPE_OLD,SUMM_EFF_DTE_INVERSE,SUMM_EFF_DATE_SRCE,SUMM_PLATE_EXPIRE_DTE,SUMM_LAST_NAME_F,
SUMM_LAST_NAME_S,SUMM_FIRST_NAME,SUMM_MULT_TERM_DATE,SUMM_MULT_OWNER_NO,SUMM_NEXT_ACTION_DTE,SUMM_RPP_IND,SUMM_AGENCY_CODE,SUMM_ASSIGN_DATE,SUMM_OPEN_TICK_COUNT,SUMM_TOTAL_AMT_DUE,SUMM_UNAPPLIED_CASH,SUMM_TOTAL_INTEREST_DUE,SUMM_INTEREST_CALC_DATE,SUMM_SCOFLAW_DEF_IND,SUMM_LAST_CORR_TYPE,SUMM_LAST_LETTER_TYPE,SUMM_LAST_CORR_DATE,
SUMM_LAST_CORR_TIME,SUMM_LAST_CORR_CLERK,SUMM_NAME,SUMM_ADDRESS_LINE_1,SUMM_ADDRESS_LINE_2,SUMM_COUNTRY,SUMM_CITY,SUMM_STATE,SUMM_ZIP_CODE,SUMM_SEX,SUMM_EYE_CODE,SUMM_HEIGHT,SUMM_WEIGHT,SUMM_RACE,SUMM_DATE_OF_BIRTH,SUMM_REQUEST_DATE,SUMM_CONFIRM_DATE,SUMM_ADDRESS_STATUS,SUMM_HOLD_TICK_CNT,SUMM_HOLD_DATE,SUMM_HOLD_AMT,
SUMM_HOLD_ELIG_CNT,SUMM_VIN_NUMBER,SUMM_HOLD_STATUS,SUMM_REG_HOLD_ID_NO,SUMM_REG_PROCESS_DATE,SUMM_SWAP_STATUS,SUMM_SWAP_DATE,SUMM_NIXIE_STATUS,SUMM_NIXIE_DATE,SUMM_NIXIE_TICK_CNT,SUMM_LAST_SEIZ_DATE,SUMM_SEIZ_STATUS,SUMM_SEIZ_STAT_DATE,SUMM_BOOTBL_TICK_CNT,SUMM_BOOTBL_AMT_DUE,SUMM_SEIZ_ELIG_CNT,SUMM_EXCLUDE_IND,
SUMM_EXCLUDE_DATE,SUMM_EXCLUDE_TIME,SUMM_EXCLUDE_AGENCY,SUMM_EXCLUDE_FILLER,SUMM_PHONE_NUMBER_FILLER,SUMM_PHONE_STATUS,SUMM_PHONE_STATUS_DATE,SUMM_PHONE_COMMENTS,SUMM_PHONE_HIST_IND,SUMM_PHONE_FILLER,SUMM_TIME_PAY_IND,SUMM_ALT_NAME_IND,SUMM_COMBINE_IND,SUMM_PLATE_SUB_TYPE,SUMM_ARCHIVE_IND,SUMM_ENTITY_HISTORY_IND,SUMM_CORPORATE_NAME_IND,
SUMM_MULT_SPLIT_IND,SUMM_IPP_HISTORY_IND,SUMM_HOLD_REASON,SUMM_IPP_INELIG_IND,SUMM_MULTI_ACTIVE_TERM,SUMM_LAST_MAIL_TYPE,SUMM_BAD_CHECK_IND,SUMM_PHONE_OP_CL_IND,SUMM_NCOA_REQ_IND,SUMM_MOVING_NAME_IND,SUMM_IMAGE_IND,SUMM_PREV_MARKED_STATUS,SUMM_HAIR_COLOR,SUMM_CLIENT_IND,SUMM_FILLER_20,SUMM_LAST_MAIL_DATE,SUMM_SSN,SUMM_ENTITY_NEXT_DTE,
SUMM_ENTITY_NEXT_TYPE,SUMM_CB_ENROLL_DATE,SUMM_CB_STATUS,SUMM_CB_STATUS_DATE,SUMM_CB_AMOUNT_DUE,SUMM_CB_COUNT,SUMM_CB_ACCOUNT,SUMM_MULTI_ENROLL_PROCDTE,SUMM_MULTI_TERM_PROCDTE,SUMM_LAST_ISSUE_DATE_INV,SUMM_TELEPHONE_NUMBER,SUMM_EMAIL_ADDRESS,SUMM_TICKET_COUNT,SUMM_COMBINE_TYPE,SUMM_COMBINE_DATE,SUMM_COMBINE_TIME,SUMM_COMBINE_USERID,SUMM_ADDRESS_USERID,
SUMM_IPP_NUMBER,SUMM_IPP_TICK_COUNT,SUMM_IPP_AMT_DUE,SUMM_IPP_DATE,SUMM_FILLER_DATE,SUMM_OWNERSHIP_DATE,SUMM_IPP_STATUS,SUMM_COMMENT_IND,SUMM_COURT_KEY_IND,SUMM_FILLER_24,NEXT_ENTITY_NUMBER,OP_STATUS,ETL_STATUS_CD,ETL_SEQ_CD,TIMS_TIMESTAMP,SRC_ROWID)
select ts.ISN,ts.SUMM_ENTITY_NUMBER,ts.SUMM_REC_NUMBER,ts.SUMM_TICKET_TYPE,ts.SUMM_STATE_DRIVER_LIC,ts.SUMM_DRIVER_LIC_CLASS,ts.SUMM_HOME_IND,ts.SUMM_SAVE_STATE_PLATE,ts.SUMM_STATE_PLATE,ts.SUMM_PLATE_TYPE,ts.SUMM_PLATE_TYPE_OLD,ts.SUMM_EFF_DTE_INVERSE,ts.SUMM_EFF_DATE_SRCE,ts.SUMM_PLATE_EXPIRE_DTE,ts.SUMM_LAST_NAME_F,
ts.SUMM_LAST_NAME_S,ts.SUMM_FIRST_NAME,ts.SUMM_MULT_TERM_DATE,ts.SUMM_MULT_OWNER_NO,ts.SUMM_NEXT_ACTION_DTE,ts.SUMM_RPP_IND,ts.SUMM_AGENCY_CODE,ts.SUMM_ASSIGN_DATE,ts.SUMM_OPEN_TICK_COUNT,ts.SUMM_TOTAL_AMT_DUE,ts.SUMM_UNAPPLIED_CASH,ts.SUMM_TOTAL_INTEREST_DUE,ts.SUMM_INTEREST_CALC_DATE,ts.SUMM_SCOFLAW_DEF_IND,ts.SUMM_LAST_CORR_TYPE,
ts.SUMM_LAST_LETTER_TYPE,ts.SUMM_LAST_CORR_DATE,ts.SUMM_LAST_CORR_TIME,ts.SUMM_LAST_CORR_CLERK,ts.SUMM_NAME,ts.SUMM_ADDRESS_LINE_1,ts.SUMM_ADDRESS_LINE_2,ts.SUMM_COUNTRY,ts.SUMM_CITY,ts.SUMM_STATE,ts.SUMM_ZIP_CODE,ts.SUMM_SEX,ts.SUMM_EYE_CODE,ts.SUMM_HEIGHT,ts.SUMM_WEIGHT,ts.SUMM_RACE,ts.SUMM_DATE_OF_BIRTH,ts.SUMM_REQUEST_DATE,ts.SUMM_CONFIRM_DATE,ts.SUMM_ADDRESS_STATUS,ts.SUMM_HOLD_TICK_CNT,ts.SUMM_HOLD_DATE,ts.SUMM_HOLD_AMT,
ts.SUMM_HOLD_ELIG_CNT,ts.SUMM_VIN_NUMBER,ts.SUMM_HOLD_STATUS,ts.SUMM_REG_HOLD_ID_NO,ts.SUMM_REG_PROCESS_DATE,ts.SUMM_SWAP_STATUS,ts.SUMM_SWAP_DATE,ts.SUMM_NIXIE_STATUS,ts.SUMM_NIXIE_DATE,ts.SUMM_NIXIE_TICK_CNT,ts.SUMM_LAST_SEIZ_DATE,ts.SUMM_SEIZ_STATUS,ts.SUMM_SEIZ_STAT_DATE,ts.SUMM_BOOTBL_TICK_CNT,ts.SUMM_BOOTBL_AMT_DUE,ts.SUMM_SEIZ_ELIG_CNT,ts.SUMM_EXCLUDE_IND,
ts.SUMM_EXCLUDE_DATE,ts.SUMM_EXCLUDE_TIME,ts.SUMM_EXCLUDE_AGENCY,ts.SUMM_EXCLUDE_FILLER,ts.SUMM_PHONE_NUMBER_FILLER,ts.SUMM_PHONE_STATUS,ts.SUMM_PHONE_STATUS_DATE,ts.SUMM_PHONE_COMMENTS,ts.SUMM_PHONE_HIST_IND,ts.SUMM_PHONE_FILLER,ts.SUMM_TIME_PAY_IND,ts.SUMM_ALT_NAME_IND,ts.SUMM_COMBINE_IND,ts.SUMM_PLATE_SUB_TYPE,ts.SUMM_ARCHIVE_IND,ts.SUMM_ENTITY_HISTORY_IND,ts.SUMM_CORPORATE_NAME_IND,
ts.SUMM_MULT_SPLIT_IND,ts.SUMM_IPP_HISTORY_IND,ts.SUMM_HOLD_REASON,ts.SUMM_IPP_INELIG_IND,ts.SUMM_MULTI_ACTIVE_TERM,ts.SUMM_LAST_MAIL_TYPE,ts.SUMM_BAD_CHECK_IND,ts.SUMM_PHONE_OP_CL_IND,ts.SUMM_NCOA_REQ_IND,ts.SUMM_MOVING_NAME_IND,ts.SUMM_IMAGE_IND,ts.SUMM_PREV_MARKED_STATUS,ts.SUMM_HAIR_COLOR,ts.SUMM_CLIENT_IND,ts.SUMM_FILLER_20,ts.SUMM_LAST_MAIL_DATE,ts.SUMM_SSN,ts.SUMM_ENTITY_NEXT_DTE,
ts.SUMM_ENTITY_NEXT_TYPE,ts.SUMM_CB_ENROLL_DATE,ts.SUMM_CB_STATUS,ts.SUMM_CB_STATUS_DATE,ts.SUMM_CB_AMOUNT_DUE,ts.SUMM_CB_COUNT,ts.SUMM_CB_ACCOUNT,ts.SUMM_MULTI_ENROLL_PROCDTE,ts.SUMM_MULTI_TERM_PROCDTE,ts.SUMM_LAST_ISSUE_DATE_INV,ts.SUMM_TELEPHONE_NUMBER,ts.SUMM_EMAIL_ADDRESS,ts.SUMM_TICKET_COUNT,ts.SUMM_COMBINE_TYPE,ts.SUMM_COMBINE_DATE,ts.SUMM_COMBINE_TIME,ts.SUMM_COMBINE_USERID,
ts.SUMM_ADDRESS_USERID,ts.SUMM_IPP_NUMBER,ts.SUMM_IPP_TICK_COUNT,ts.SUMM_IPP_AMT_DUE,ts.SUMM_IPP_DATE,ts.SUMM_FILLER_DATE,ts.SUMM_OWNERSHIP_DATE,ts.SUMM_IPP_STATUS,ts.SUMM_COMMENT_IND,ts.SUMM_COURT_KEY_IND,ts.SUMM_FILLER_24,ts.NEXT_ENTITY_NUMBER,ts.OP_STATUS,ts.ETL_STATUS_CD,ts.ETL_SEQ_CD,ts.TIMS_TIMESTAMP,rowid as src_rowid 
from stg_columbus_dtl.TM2_TICKET_SUMMARY@stg_dblink ts
where ts.etl_status_cd=15 AND ts.op_status IN ('INSERT','DELETE','UPDATE','SQL COMPUPDATE');

insert into stg_tm2_ticket_summary (ISN,SUMM_ENTITY_NUMBER,SUMM_REC_NUMBER,SUMM_TICKET_TYPE,SUMM_STATE_DRIVER_LIC,SUMM_DRIVER_LIC_CLASS,SUMM_HOME_IND,SUMM_SAVE_STATE_PLATE,SUMM_STATE_PLATE,SUMM_PLATE_TYPE,SUMM_PLATE_TYPE_OLD,SUMM_EFF_DTE_INVERSE,SUMM_EFF_DATE_SRCE,SUMM_PLATE_EXPIRE_DTE,SUMM_LAST_NAME_F,
SUMM_LAST_NAME_S,SUMM_FIRST_NAME,SUMM_MULT_TERM_DATE,SUMM_MULT_OWNER_NO,SUMM_NEXT_ACTION_DTE,SUMM_RPP_IND,SUMM_AGENCY_CODE,SUMM_ASSIGN_DATE,SUMM_OPEN_TICK_COUNT,SUMM_TOTAL_AMT_DUE,SUMM_UNAPPLIED_CASH,SUMM_TOTAL_INTEREST_DUE,SUMM_INTEREST_CALC_DATE,SUMM_SCOFLAW_DEF_IND,SUMM_LAST_CORR_TYPE,SUMM_LAST_LETTER_TYPE,SUMM_LAST_CORR_DATE,
SUMM_LAST_CORR_TIME,SUMM_LAST_CORR_CLERK,SUMM_NAME,SUMM_ADDRESS_LINE_1,SUMM_ADDRESS_LINE_2,SUMM_COUNTRY,SUMM_CITY,SUMM_STATE,SUMM_ZIP_CODE,SUMM_SEX,SUMM_EYE_CODE,SUMM_HEIGHT,SUMM_WEIGHT,SUMM_RACE,SUMM_DATE_OF_BIRTH,SUMM_REQUEST_DATE,SUMM_CONFIRM_DATE,SUMM_ADDRESS_STATUS,SUMM_HOLD_TICK_CNT,SUMM_HOLD_DATE,SUMM_HOLD_AMT,
SUMM_HOLD_ELIG_CNT,SUMM_VIN_NUMBER,SUMM_HOLD_STATUS,SUMM_REG_HOLD_ID_NO,SUMM_REG_PROCESS_DATE,SUMM_SWAP_STATUS,SUMM_SWAP_DATE,SUMM_NIXIE_STATUS,SUMM_NIXIE_DATE,SUMM_NIXIE_TICK_CNT,SUMM_LAST_SEIZ_DATE,SUMM_SEIZ_STATUS,SUMM_SEIZ_STAT_DATE,SUMM_BOOTBL_TICK_CNT,SUMM_BOOTBL_AMT_DUE,SUMM_SEIZ_ELIG_CNT,SUMM_EXCLUDE_IND,
SUMM_EXCLUDE_DATE,SUMM_EXCLUDE_TIME,SUMM_EXCLUDE_AGENCY,SUMM_EXCLUDE_FILLER,SUMM_PHONE_NUMBER_FILLER,SUMM_PHONE_STATUS,SUMM_PHONE_STATUS_DATE,SUMM_PHONE_COMMENTS,SUMM_PHONE_HIST_IND,SUMM_PHONE_FILLER,SUMM_TIME_PAY_IND,SUMM_ALT_NAME_IND,SUMM_COMBINE_IND,SUMM_PLATE_SUB_TYPE,SUMM_ARCHIVE_IND,SUMM_ENTITY_HISTORY_IND,SUMM_CORPORATE_NAME_IND,
SUMM_MULT_SPLIT_IND,SUMM_IPP_HISTORY_IND,SUMM_HOLD_REASON,SUMM_IPP_INELIG_IND,SUMM_MULTI_ACTIVE_TERM,SUMM_LAST_MAIL_TYPE,SUMM_BAD_CHECK_IND,SUMM_PHONE_OP_CL_IND,SUMM_NCOA_REQ_IND,SUMM_MOVING_NAME_IND,SUMM_IMAGE_IND,SUMM_PREV_MARKED_STATUS,SUMM_HAIR_COLOR,SUMM_CLIENT_IND,SUMM_FILLER_20,SUMM_LAST_MAIL_DATE,SUMM_SSN,SUMM_ENTITY_NEXT_DTE,
SUMM_ENTITY_NEXT_TYPE,SUMM_CB_ENROLL_DATE,SUMM_CB_STATUS,SUMM_CB_STATUS_DATE,SUMM_CB_AMOUNT_DUE,SUMM_CB_COUNT,SUMM_CB_ACCOUNT,SUMM_MULTI_ENROLL_PROCDTE,SUMM_MULTI_TERM_PROCDTE,SUMM_LAST_ISSUE_DATE_INV,SUMM_TELEPHONE_NUMBER,SUMM_EMAIL_ADDRESS,SUMM_TICKET_COUNT,SUMM_COMBINE_TYPE,SUMM_COMBINE_DATE,SUMM_COMBINE_TIME,SUMM_COMBINE_USERID,SUMM_ADDRESS_USERID,
SUMM_IPP_NUMBER,SUMM_IPP_TICK_COUNT,SUMM_IPP_AMT_DUE,SUMM_IPP_DATE,SUMM_FILLER_DATE,SUMM_OWNERSHIP_DATE,SUMM_IPP_STATUS,SUMM_COMMENT_IND,SUMM_COURT_KEY_IND,SUMM_FILLER_24,NEXT_ENTITY_NUMBER,OP_STATUS,ETL_STATUS_CD,ETL_SEQ_CD,TIMS_TIMESTAMP) 
select ISN,SUMM_ENTITY_NUMBER,SUMM_REC_NUMBER,SUMM_TICKET_TYPE,SUMM_STATE_DRIVER_LIC,SUMM_DRIVER_LIC_CLASS,SUMM_HOME_IND,SUMM_SAVE_STATE_PLATE,SUMM_STATE_PLATE,SUMM_PLATE_TYPE,SUMM_PLATE_TYPE_OLD,SUMM_EFF_DTE_INVERSE,SUMM_EFF_DATE_SRCE,SUMM_PLATE_EXPIRE_DTE,SUMM_LAST_NAME_F,
SUMM_LAST_NAME_S,SUMM_FIRST_NAME,SUMM_MULT_TERM_DATE,SUMM_MULT_OWNER_NO,SUMM_NEXT_ACTION_DTE,SUMM_RPP_IND,SUMM_AGENCY_CODE,SUMM_ASSIGN_DATE,SUMM_OPEN_TICK_COUNT,SUMM_TOTAL_AMT_DUE,SUMM_UNAPPLIED_CASH,SUMM_TOTAL_INTEREST_DUE,SUMM_INTEREST_CALC_DATE,SUMM_SCOFLAW_DEF_IND,SUMM_LAST_CORR_TYPE,SUMM_LAST_LETTER_TYPE,SUMM_LAST_CORR_DATE,
SUMM_LAST_CORR_TIME,SUMM_LAST_CORR_CLERK,SUMM_NAME,SUMM_ADDRESS_LINE_1,SUMM_ADDRESS_LINE_2,SUMM_COUNTRY,SUMM_CITY,SUMM_STATE,SUMM_ZIP_CODE,SUMM_SEX,SUMM_EYE_CODE,SUMM_HEIGHT,SUMM_WEIGHT,SUMM_RACE,SUMM_DATE_OF_BIRTH,SUMM_REQUEST_DATE,SUMM_CONFIRM_DATE,SUMM_ADDRESS_STATUS,SUMM_HOLD_TICK_CNT,SUMM_HOLD_DATE,SUMM_HOLD_AMT,
SUMM_HOLD_ELIG_CNT,SUMM_VIN_NUMBER,SUMM_HOLD_STATUS,SUMM_REG_HOLD_ID_NO,SUMM_REG_PROCESS_DATE,SUMM_SWAP_STATUS,SUMM_SWAP_DATE,SUMM_NIXIE_STATUS,SUMM_NIXIE_DATE,SUMM_NIXIE_TICK_CNT,SUMM_LAST_SEIZ_DATE,SUMM_SEIZ_STATUS,SUMM_SEIZ_STAT_DATE,SUMM_BOOTBL_TICK_CNT,SUMM_BOOTBL_AMT_DUE,SUMM_SEIZ_ELIG_CNT,SUMM_EXCLUDE_IND,
SUMM_EXCLUDE_DATE,SUMM_EXCLUDE_TIME,SUMM_EXCLUDE_AGENCY,SUMM_EXCLUDE_FILLER,SUMM_PHONE_NUMBER_FILLER,SUMM_PHONE_STATUS,SUMM_PHONE_STATUS_DATE,SUMM_PHONE_COMMENTS,SUMM_PHONE_HIST_IND,SUMM_PHONE_FILLER,SUMM_TIME_PAY_IND,SUMM_ALT_NAME_IND,SUMM_COMBINE_IND,SUMM_PLATE_SUB_TYPE,SUMM_ARCHIVE_IND,SUMM_ENTITY_HISTORY_IND,SUMM_CORPORATE_NAME_IND,
SUMM_MULT_SPLIT_IND,SUMM_IPP_HISTORY_IND,SUMM_HOLD_REASON,SUMM_IPP_INELIG_IND,SUMM_MULTI_ACTIVE_TERM,SUMM_LAST_MAIL_TYPE,SUMM_BAD_CHECK_IND,SUMM_PHONE_OP_CL_IND,SUMM_NCOA_REQ_IND,SUMM_MOVING_NAME_IND,SUMM_IMAGE_IND,SUMM_PREV_MARKED_STATUS,SUMM_HAIR_COLOR,SUMM_CLIENT_IND,SUMM_FILLER_20,SUMM_LAST_MAIL_DATE,SUMM_SSN,SUMM_ENTITY_NEXT_DTE,
SUMM_ENTITY_NEXT_TYPE,SUMM_CB_ENROLL_DATE,SUMM_CB_STATUS,SUMM_CB_STATUS_DATE,SUMM_CB_AMOUNT_DUE,SUMM_CB_COUNT,SUMM_CB_ACCOUNT,SUMM_MULTI_ENROLL_PROCDTE,SUMM_MULTI_TERM_PROCDTE,SUMM_LAST_ISSUE_DATE_INV,SUMM_TELEPHONE_NUMBER,SUMM_EMAIL_ADDRESS,SUMM_TICKET_COUNT,SUMM_COMBINE_TYPE,SUMM_COMBINE_DATE,SUMM_COMBINE_TIME,SUMM_COMBINE_USERID,SUMM_ADDRESS_USERID,
SUMM_IPP_NUMBER,SUMM_IPP_TICK_COUNT,SUMM_IPP_AMT_DUE,SUMM_IPP_DATE,SUMM_FILLER_DATE,SUMM_OWNERSHIP_DATE,SUMM_IPP_STATUS,SUMM_COMMENT_IND,SUMM_COURT_KEY_IND,SUMM_FILLER_24,NEXT_ENTITY_NUMBER,OP_STATUS,ETL_STATUS_CD,ETL_SEQ_CD,TIMS_TIMESTAMP
from stg_columbus_dtl.TM2_TICKET_SUMMARY@stg_dblink ts where ts.etl_status_cd=15;

commit;

--*** Arvind/ Meeting from 02/07/2020 moving ticket stage data collected into tmep daily tables

truncate table todays_tick_list_stage reuse storage; 
truncate table todays_tick_list_stage2 reuse storage; 
truncate table todays_catchup_tick_segment2 reuse storage;
truncate table todays_catchup_tick_segment reuse storage;


--****NOT TAKING DELETES - COLUMBUS: We don't delete tickets


--This criteria may be redundant, but keeping it. (Status has stayed=10)
insert into todays_tick_list_stage2
SELECT tick_number from stg_columbus_dtl.tick_segment@stg_dblink s
where ETL_STATUS_CD=15 AND s.OP_STATUS IN ( 'INSERT','UPDATE','SQL COMPUPDATE' );

COMMIT;

insert into todays_catchup_tick_segment (ISN,IDX,TICK_NUMBER,AMOUNT_DUE,SAMPLE_IND,STATE_PLATE,PLATE_TYPE,EFFECTIVE_DATE,PLATE_YEAR,PLATE_EXP_DATE,SEIZE_IND,BOOT_IND,RENTAL_IND,UNAPPLIED_AMT,DATE_OF_BIRTH,MORE_UNAPPLIED,INTEREST_DUE,HOLD_REQUEST_DATE,ASSIGN_AGENCY,ASSIGN_DATE,ASSIGN_STATUS,ASSIGN_AMOUNT,SWAP_DATE,LAST_NAME,ISSUE_COMMENTS,IDENT_ALF_FILL2,IDENT_NUM_FILL1,
IDENT_NUM_FILL2,ISSUE_DATE,BADGE_ISSUED,AGENCY,DIVISION,VIOLATION_CODE,VIOLATION_TYPE,SPEED_ZONE,SPEED_ACTUAL,OVERWEIGHT,RADAR_IND,BOOKED_IND,ACCIDENT,HAZARD,FINE_AMOUNT,LOCATION,ROUTE,MAKE,COLOR,BODY_STYLE,ISSUE_TIME_1,ISSUE_TIME_2,VEHICLE_TYPE,METER,OTHER_VIOLATION,LATITUDE,LONGITUDE,DATA_FILL_2,DATA_FILL_3,POINTS,RESCHED_REASON_CNT1,RESCHED_REASON_CNT2,PROCESS_DATE,
BATCH_NUMBER,BATCH_DATE,NEXT_ACTION_DTE,NEXT_ACTION_TYP,MICROFILM_NO,BACKLOG_CODE,CITY_REF_NO,ERROR_FLAGS,EVENT_FLAGS_2,EVENT_FLAGS,DATA_ALF_FILL1,DATA_ALF_FILL2,DATA_ALF_FILL3,DATA_NUM_FILL1,DATA_NUM_FILL2,DATA_NUM_FILL3,ERROR_CODE,INVOICE_IND,PENALTY_1,PENALTY_2,PENALTY_3,PENALTY_4,PENALTY_5,REGISTRY_MAKE,REG_CONFIRM_DTE,NIXIE_DATE,NIXIE_STATUS,VIN_NUMBER,HOLD_STATUS,
HOLD_PROC_DATE,HOLD_ID_NUMBER,PAYMENT_TYPE,DEPOSIT_DATE,PAYMENT_AMOUNT,PAYMENT_METHOD,PAYMENT_AGENCY,PAYMENT_CLERK,PAY_PROCESS_DTE,PAY_BATCH_NUM,PAY_NOTICE_TYPE,ACCOUNT_NUMBER,REFUND_CHECK_NO,MORE_PAYMENTS,REAPPLY_SOURCE,PAY_ALF_FILL2,PAY_NUM_FILL1,PAY_NUM_FILL2,NOTICE_TYPE_1,NOTICE_DATE_1,NOTICE_PROC_DATE_1,NOTICE_TYPE_2,NOTICE_DATE_2,NOTICE_PROC_DATE_2,NOTICE_TYPE_3,
NOTICE_DATE_3,NOTICE_PROC_DATE_3,NOTICE_TYPE_4,NOTICE_DATE_4,NOTICE_PROC_DATE_4,NOTICE_TYPE_5,NOTICE_DATE_5,NOTICE_PROC_DATE_5,MORE_NOTICES,NOTE_ALF_FILL1,NOTE_ALF_FILL2,NOTE_NUM_FILL1,NOTE_NUM_FILL2,SUSPEND_DATE,SUSPEND_TIME,SUSPEND_CLRK_ID,SUSPEND_CODE,SUSPEND_TIL_DTE,SUSPEND_PROCESS_DTE,MORE_SUSPENDS,SUSP_COMMENTS,SUSP_ALF_FILL2,SUSP_NUM_FILL1,SUSP_NUM_FILL2,
HEARING_OFFICER,HEARING_DATE,HEARING_TIME,HEARING_CLERK,HEARING_PROCESS_DTE,HEARING_PROCESS_TIM,HEARING_REQUIRED,PLEA_CODE,REDUCTION_AMOUNT,HEAR_DISPOSITN,DISPOSITION_DATE,DISPOSITION_CLERK,DISPO_PROCESS_DTE,DISPO_PROCESS_TIME,MORE_HEARINGS,CHANGES_MADE,CHANGE_DATE,HEAR_COMMENTS,HEAR_ALF_FILL2,DISPOSITION_BATCH,HEAR_NUM_FILL2,CORR_TYPE,LETTER_TYPE,CORR_DATE,CORR_TIME,
CORR_CLERK,MORE_CORRESPON,CORR_EMAIL_ADDRESS,CORR_PHONE_NUMBER,CORR_IMAGE_IND,CORR_NUM_FILL1,CORR_NUM_FILL2,NAME,ADDRESS_LINE_1,ADDRESS_LINE_2,COUNTRY,CITY,STATE,ZIP,NAME_REASON,PATROL_ZONE,CASE_NO,ACCIDENT_NO,ARCHIVE_IND,PLATE_COLOR,RMV_PLATE_COLOR,SUB_PLATE_TYPE,RMV_ERROR_CODE,SWAP_IND,HOLD_REASON,MAIL_COUNTS,VEHICLE_YEAR,PLATE_COLOR_DEFAULT,CORR_SENT_IND,RESTORE_IND,
IPP_IND,HEAR_SCHED_COUNT,DOCU_NO,CHANGE_SOURCE,FILL_20,LIEN_RESOLVED,REALTIME_IND,MISC_ALF_FILL3,MISC_ALF_FILL4,REGISTRY_STATUS,BOOT_EXCLUDE,IPP_ENROLL_AMT,CLIENT_DATE,CLIENT_AREA,CLIENT_ALF_FILL,CLIENT_NUM_FILL,IPP_DEFAULT_IND,MISC_NUM_FILL6,MISC_NUM_FILL7,MISC_NUM_FILL8,PAY_PROCESS_TIME,REG_REQUEST_DATE,ALT_ISSUE_DATE,CB_ENROLL_DATE,CB_STATUS,CB_COMMENT,FIRST_NAME,
RPP_PERMIT_NUMBER,IMAGE_IND,PENALTY_DATE1,PENALTY_DATE2,PENALTY_DATE3,PENALTY_DATE4,PENALTY_DATE5,DRIVEAWAY_FLAG,VEH_MODEL,VEH_YEAR_MONTH,HH_PLATE_EXP_DATE,COA_SOURCE,COMMENT_IND,OP_STATUS,ETL_STATUS_CD,ETL_SEQ_CD,TIMS_TIMESTAMP)
select ISN,IDX,TICK_NUMBER,AMOUNT_DUE,SAMPLE_IND,STATE_PLATE,PLATE_TYPE,EFFECTIVE_DATE,PLATE_YEAR,PLATE_EXP_DATE,SEIZE_IND,BOOT_IND,RENTAL_IND,UNAPPLIED_AMT,DATE_OF_BIRTH,MORE_UNAPPLIED,INTEREST_DUE,HOLD_REQUEST_DATE,ASSIGN_AGENCY,ASSIGN_DATE,ASSIGN_STATUS,ASSIGN_AMOUNT,SWAP_DATE,LAST_NAME,ISSUE_COMMENTS,IDENT_ALF_FILL2,IDENT_NUM_FILL1,
IDENT_NUM_FILL2,ISSUE_DATE,BADGE_ISSUED,AGENCY,DIVISION,VIOLATION_CODE,VIOLATION_TYPE,SPEED_ZONE,SPEED_ACTUAL,OVERWEIGHT,RADAR_IND,BOOKED_IND,ACCIDENT,HAZARD,FINE_AMOUNT,LOCATION,ROUTE,MAKE,COLOR,BODY_STYLE,ISSUE_TIME_1,ISSUE_TIME_2,VEHICLE_TYPE,METER,OTHER_VIOLATION,LATITUDE,LONGITUDE,DATA_FILL_2,DATA_FILL_3,POINTS,RESCHED_REASON_CNT1,RESCHED_REASON_CNT2,PROCESS_DATE,
BATCH_NUMBER,BATCH_DATE,NEXT_ACTION_DTE,NEXT_ACTION_TYP,MICROFILM_NO,BACKLOG_CODE,CITY_REF_NO,ERROR_FLAGS,EVENT_FLAGS_2,EVENT_FLAGS,DATA_ALF_FILL1,DATA_ALF_FILL2,DATA_ALF_FILL3,DATA_NUM_FILL1,DATA_NUM_FILL2,DATA_NUM_FILL3,ERROR_CODE,INVOICE_IND,PENALTY_1,PENALTY_2,PENALTY_3,PENALTY_4,PENALTY_5,REGISTRY_MAKE,REG_CONFIRM_DTE,NIXIE_DATE,NIXIE_STATUS,VIN_NUMBER,HOLD_STATUS,
HOLD_PROC_DATE,HOLD_ID_NUMBER,PAYMENT_TYPE,DEPOSIT_DATE,PAYMENT_AMOUNT,PAYMENT_METHOD,PAYMENT_AGENCY,PAYMENT_CLERK,PAY_PROCESS_DTE,PAY_BATCH_NUM,PAY_NOTICE_TYPE,ACCOUNT_NUMBER,REFUND_CHECK_NO,MORE_PAYMENTS,REAPPLY_SOURCE,PAY_ALF_FILL2,PAY_NUM_FILL1,PAY_NUM_FILL2,NOTICE_TYPE_1,NOTICE_DATE_1,NOTICE_PROC_DATE_1,NOTICE_TYPE_2,NOTICE_DATE_2,NOTICE_PROC_DATE_2,NOTICE_TYPE_3,
NOTICE_DATE_3,NOTICE_PROC_DATE_3,NOTICE_TYPE_4,NOTICE_DATE_4,NOTICE_PROC_DATE_4,NOTICE_TYPE_5,NOTICE_DATE_5,NOTICE_PROC_DATE_5,MORE_NOTICES,NOTE_ALF_FILL1,NOTE_ALF_FILL2,NOTE_NUM_FILL1,NOTE_NUM_FILL2,SUSPEND_DATE,SUSPEND_TIME,SUSPEND_CLRK_ID,SUSPEND_CODE,SUSPEND_TIL_DTE,SUSPEND_PROCESS_DTE,MORE_SUSPENDS,SUSP_COMMENTS,SUSP_ALF_FILL2,SUSP_NUM_FILL1,SUSP_NUM_FILL2,
HEARING_OFFICER,HEARING_DATE,HEARING_TIME,HEARING_CLERK,HEARING_PROCESS_DTE,HEARING_PROCESS_TIM,HEARING_REQUIRED,PLEA_CODE,REDUCTION_AMOUNT,HEAR_DISPOSITN,DISPOSITION_DATE,DISPOSITION_CLERK,DISPO_PROCESS_DTE,DISPO_PROCESS_TIME,MORE_HEARINGS,CHANGES_MADE,CHANGE_DATE,HEAR_COMMENTS,HEAR_ALF_FILL2,DISPOSITION_BATCH,HEAR_NUM_FILL2,CORR_TYPE,LETTER_TYPE,CORR_DATE,CORR_TIME,
CORR_CLERK,MORE_CORRESPON,CORR_EMAIL_ADDRESS,CORR_PHONE_NUMBER,CORR_IMAGE_IND,CORR_NUM_FILL1,CORR_NUM_FILL2,NAME,ADDRESS_LINE_1,ADDRESS_LINE_2,COUNTRY,CITY,STATE,ZIP,NAME_REASON,PATROL_ZONE,CASE_NO,ACCIDENT_NO,ARCHIVE_IND,PLATE_COLOR,RMV_PLATE_COLOR,SUB_PLATE_TYPE,RMV_ERROR_CODE,SWAP_IND,HOLD_REASON,MAIL_COUNTS,VEHICLE_YEAR,PLATE_COLOR_DEFAULT,CORR_SENT_IND,RESTORE_IND,
IPP_IND,HEAR_SCHED_COUNT,DOCU_NO,CHANGE_SOURCE,FILL_20,LIEN_RESOLVED,REALTIME_IND,MISC_ALF_FILL3,MISC_ALF_FILL4,REGISTRY_STATUS,BOOT_EXCLUDE,IPP_ENROLL_AMT,CLIENT_DATE,CLIENT_AREA,CLIENT_ALF_FILL,CLIENT_NUM_FILL,IPP_DEFAULT_IND,MISC_NUM_FILL6,MISC_NUM_FILL7,MISC_NUM_FILL8,PAY_PROCESS_TIME,REG_REQUEST_DATE,ALT_ISSUE_DATE,CB_ENROLL_DATE,CB_STATUS,CB_COMMENT,FIRST_NAME,
RPP_PERMIT_NUMBER,IMAGE_IND,PENALTY_DATE1,PENALTY_DATE2,PENALTY_DATE3,PENALTY_DATE4,PENALTY_DATE5,DRIVEAWAY_FLAG,VEH_MODEL,VEH_YEAR_MONTH,HH_PLATE_EXP_DATE,COA_SOURCE,COMMENT_IND,OP_STATUS,ETL_STATUS_CD,ETL_SEQ_CD,TIMS_TIMESTAMP 
from stg_columbus_dtl.tick_segment@stg_dblink
where tick_number > '0' AND etl_status_cd=15
   AND tims_timestamp >= (select last_run_date from cfg_batch_run)
   AND tims_timestamp < (select last_run_date + days_to_run from cfg_batch_run);

COMMIT;

insert into todays_catchup_tick_segment2 (ISN,IDX,TICK_NUMBER,AMOUNT_DUE,SAMPLE_IND,STATE_PLATE,PLATE_TYPE,EFFECTIVE_DATE,PLATE_YEAR,PLATE_EXP_DATE,SEIZE_IND,BOOT_IND,RENTAL_IND,UNAPPLIED_AMT,DATE_OF_BIRTH,MORE_UNAPPLIED,INTEREST_DUE,HOLD_REQUEST_DATE,ASSIGN_AGENCY,ASSIGN_DATE,ASSIGN_STATUS,ASSIGN_AMOUNT,SWAP_DATE,LAST_NAME,ISSUE_COMMENTS,IDENT_ALF_FILL2,IDENT_NUM_FILL1,
IDENT_NUM_FILL2,ISSUE_DATE,BADGE_ISSUED,AGENCY,DIVISION,VIOLATION_CODE,VIOLATION_TYPE,SPEED_ZONE,SPEED_ACTUAL,OVERWEIGHT,RADAR_IND,BOOKED_IND,ACCIDENT,HAZARD,FINE_AMOUNT,LOCATION,ROUTE,MAKE,COLOR,BODY_STYLE,ISSUE_TIME_1,ISSUE_TIME_2,VEHICLE_TYPE,METER,OTHER_VIOLATION,LATITUDE,LONGITUDE,DATA_FILL_2,DATA_FILL_3,POINTS,RESCHED_REASON_CNT1,RESCHED_REASON_CNT2,PROCESS_DATE,
BATCH_NUMBER,BATCH_DATE,NEXT_ACTION_DTE,NEXT_ACTION_TYP,MICROFILM_NO,BACKLOG_CODE,CITY_REF_NO,ERROR_FLAGS,EVENT_FLAGS_2,EVENT_FLAGS,DATA_ALF_FILL1,DATA_ALF_FILL2,DATA_ALF_FILL3,DATA_NUM_FILL1,DATA_NUM_FILL2,DATA_NUM_FILL3,ERROR_CODE,INVOICE_IND,PENALTY_1,PENALTY_2,PENALTY_3,PENALTY_4,PENALTY_5,REGISTRY_MAKE,REG_CONFIRM_DTE,NIXIE_DATE,NIXIE_STATUS,VIN_NUMBER,HOLD_STATUS,
HOLD_PROC_DATE,HOLD_ID_NUMBER,PAYMENT_TYPE,DEPOSIT_DATE,PAYMENT_AMOUNT,PAYMENT_METHOD,PAYMENT_AGENCY,PAYMENT_CLERK,PAY_PROCESS_DTE,PAY_BATCH_NUM,PAY_NOTICE_TYPE,ACCOUNT_NUMBER,REFUND_CHECK_NO,MORE_PAYMENTS,REAPPLY_SOURCE,PAY_ALF_FILL2,PAY_NUM_FILL1,PAY_NUM_FILL2,NOTICE_TYPE_1,NOTICE_DATE_1,NOTICE_PROC_DATE_1,NOTICE_TYPE_2,NOTICE_DATE_2,NOTICE_PROC_DATE_2,NOTICE_TYPE_3,
NOTICE_DATE_3,NOTICE_PROC_DATE_3,NOTICE_TYPE_4,NOTICE_DATE_4,NOTICE_PROC_DATE_4,NOTICE_TYPE_5,NOTICE_DATE_5,NOTICE_PROC_DATE_5,MORE_NOTICES,NOTE_ALF_FILL1,NOTE_ALF_FILL2,NOTE_NUM_FILL1,NOTE_NUM_FILL2,SUSPEND_DATE,SUSPEND_TIME,SUSPEND_CLRK_ID,SUSPEND_CODE,SUSPEND_TIL_DTE,SUSPEND_PROCESS_DTE,MORE_SUSPENDS,SUSP_COMMENTS,SUSP_ALF_FILL2,SUSP_NUM_FILL1,SUSP_NUM_FILL2,
HEARING_OFFICER,HEARING_DATE,HEARING_TIME,HEARING_CLERK,HEARING_PROCESS_DTE,HEARING_PROCESS_TIM,HEARING_REQUIRED,PLEA_CODE,REDUCTION_AMOUNT,HEAR_DISPOSITN,DISPOSITION_DATE,DISPOSITION_CLERK,DISPO_PROCESS_DTE,DISPO_PROCESS_TIME,MORE_HEARINGS,CHANGES_MADE,CHANGE_DATE,HEAR_COMMENTS,HEAR_ALF_FILL2,DISPOSITION_BATCH,HEAR_NUM_FILL2,CORR_TYPE,LETTER_TYPE,CORR_DATE,CORR_TIME,
CORR_CLERK,MORE_CORRESPON,CORR_EMAIL_ADDRESS,CORR_PHONE_NUMBER,CORR_IMAGE_IND,CORR_NUM_FILL1,CORR_NUM_FILL2,NAME,ADDRESS_LINE_1,ADDRESS_LINE_2,COUNTRY,CITY,STATE,ZIP,NAME_REASON,PATROL_ZONE,CASE_NO,ACCIDENT_NO,ARCHIVE_IND,PLATE_COLOR,RMV_PLATE_COLOR,SUB_PLATE_TYPE,RMV_ERROR_CODE,SWAP_IND,HOLD_REASON,MAIL_COUNTS,VEHICLE_YEAR,PLATE_COLOR_DEFAULT,CORR_SENT_IND,RESTORE_IND,
IPP_IND,HEAR_SCHED_COUNT,DOCU_NO,CHANGE_SOURCE,FILL_20,LIEN_RESOLVED,REALTIME_IND,MISC_ALF_FILL3,MISC_ALF_FILL4,REGISTRY_STATUS,BOOT_EXCLUDE,IPP_ENROLL_AMT,CLIENT_DATE,CLIENT_AREA,CLIENT_ALF_FILL,CLIENT_NUM_FILL,IPP_DEFAULT_IND,MISC_NUM_FILL6,MISC_NUM_FILL7,MISC_NUM_FILL8,PAY_PROCESS_TIME,REG_REQUEST_DATE,ALT_ISSUE_DATE,CB_ENROLL_DATE,CB_STATUS,CB_COMMENT,FIRST_NAME,
RPP_PERMIT_NUMBER,IMAGE_IND,PENALTY_DATE1,PENALTY_DATE2,PENALTY_DATE3,PENALTY_DATE4,PENALTY_DATE5,DRIVEAWAY_FLAG,VEH_MODEL,VEH_YEAR_MONTH,HH_PLATE_EXP_DATE,COA_SOURCE,COMMENT_IND,OP_STATUS,ETL_STATUS_CD,ETL_SEQ_CD,TIMS_TIMESTAMP,REC_NO)
 select ISN,IDX,TICK_NUMBER,AMOUNT_DUE,SAMPLE_IND,STATE_PLATE,PLATE_TYPE,EFFECTIVE_DATE,PLATE_YEAR,PLATE_EXP_DATE,SEIZE_IND,BOOT_IND,RENTAL_IND,UNAPPLIED_AMT,DATE_OF_BIRTH,MORE_UNAPPLIED,INTEREST_DUE,HOLD_REQUEST_DATE,ASSIGN_AGENCY,ASSIGN_DATE,ASSIGN_STATUS,ASSIGN_AMOUNT,SWAP_DATE,LAST_NAME,ISSUE_COMMENTS,IDENT_ALF_FILL2,IDENT_NUM_FILL1,
IDENT_NUM_FILL2,ISSUE_DATE,BADGE_ISSUED,AGENCY,DIVISION,VIOLATION_CODE,VIOLATION_TYPE,SPEED_ZONE,SPEED_ACTUAL,OVERWEIGHT,RADAR_IND,BOOKED_IND,ACCIDENT,HAZARD,FINE_AMOUNT,LOCATION,ROUTE,MAKE,COLOR,BODY_STYLE,ISSUE_TIME_1,ISSUE_TIME_2,VEHICLE_TYPE,METER,OTHER_VIOLATION,LATITUDE,LONGITUDE,DATA_FILL_2,DATA_FILL_3,POINTS,RESCHED_REASON_CNT1,RESCHED_REASON_CNT2,PROCESS_DATE,
BATCH_NUMBER,BATCH_DATE,NEXT_ACTION_DTE,NEXT_ACTION_TYP,MICROFILM_NO,BACKLOG_CODE,CITY_REF_NO,ERROR_FLAGS,EVENT_FLAGS_2,EVENT_FLAGS,DATA_ALF_FILL1,DATA_ALF_FILL2,DATA_ALF_FILL3,DATA_NUM_FILL1,DATA_NUM_FILL2,DATA_NUM_FILL3,ERROR_CODE,INVOICE_IND,PENALTY_1,PENALTY_2,PENALTY_3,PENALTY_4,PENALTY_5,REGISTRY_MAKE,REG_CONFIRM_DTE,NIXIE_DATE,NIXIE_STATUS,VIN_NUMBER,HOLD_STATUS,
HOLD_PROC_DATE,HOLD_ID_NUMBER,PAYMENT_TYPE,DEPOSIT_DATE,PAYMENT_AMOUNT,PAYMENT_METHOD,PAYMENT_AGENCY,PAYMENT_CLERK,PAY_PROCESS_DTE,PAY_BATCH_NUM,PAY_NOTICE_TYPE,ACCOUNT_NUMBER,REFUND_CHECK_NO,MORE_PAYMENTS,REAPPLY_SOURCE,PAY_ALF_FILL2,PAY_NUM_FILL1,PAY_NUM_FILL2,NOTICE_TYPE_1,NOTICE_DATE_1,NOTICE_PROC_DATE_1,NOTICE_TYPE_2,NOTICE_DATE_2,NOTICE_PROC_DATE_2,NOTICE_TYPE_3,
NOTICE_DATE_3,NOTICE_PROC_DATE_3,NOTICE_TYPE_4,NOTICE_DATE_4,NOTICE_PROC_DATE_4,NOTICE_TYPE_5,NOTICE_DATE_5,NOTICE_PROC_DATE_5,MORE_NOTICES,NOTE_ALF_FILL1,NOTE_ALF_FILL2,NOTE_NUM_FILL1,NOTE_NUM_FILL2,SUSPEND_DATE,SUSPEND_TIME,SUSPEND_CLRK_ID,SUSPEND_CODE,SUSPEND_TIL_DTE,SUSPEND_PROCESS_DTE,MORE_SUSPENDS,SUSP_COMMENTS,SUSP_ALF_FILL2,SUSP_NUM_FILL1,SUSP_NUM_FILL2,
HEARING_OFFICER,HEARING_DATE,HEARING_TIME,HEARING_CLERK,HEARING_PROCESS_DTE,HEARING_PROCESS_TIM,HEARING_REQUIRED,PLEA_CODE,REDUCTION_AMOUNT,HEAR_DISPOSITN,DISPOSITION_DATE,DISPOSITION_CLERK,DISPO_PROCESS_DTE,DISPO_PROCESS_TIME,MORE_HEARINGS,CHANGES_MADE,CHANGE_DATE,HEAR_COMMENTS,HEAR_ALF_FILL2,DISPOSITION_BATCH,HEAR_NUM_FILL2,CORR_TYPE,LETTER_TYPE,CORR_DATE,CORR_TIME,
CORR_CLERK,MORE_CORRESPON,CORR_EMAIL_ADDRESS,CORR_PHONE_NUMBER,CORR_IMAGE_IND,CORR_NUM_FILL1,CORR_NUM_FILL2,NAME,ADDRESS_LINE_1,ADDRESS_LINE_2,COUNTRY,CITY,STATE,ZIP,NAME_REASON,PATROL_ZONE,CASE_NO,ACCIDENT_NO,ARCHIVE_IND,PLATE_COLOR,RMV_PLATE_COLOR,SUB_PLATE_TYPE,RMV_ERROR_CODE,SWAP_IND,HOLD_REASON,MAIL_COUNTS,VEHICLE_YEAR,PLATE_COLOR_DEFAULT,CORR_SENT_IND,RESTORE_IND,
IPP_IND,HEAR_SCHED_COUNT,DOCU_NO,CHANGE_SOURCE,FILL_20,LIEN_RESOLVED,REALTIME_IND,MISC_ALF_FILL3,MISC_ALF_FILL4,REGISTRY_STATUS,BOOT_EXCLUDE,IPP_ENROLL_AMT,CLIENT_DATE,CLIENT_AREA,CLIENT_ALF_FILL,CLIENT_NUM_FILL,IPP_DEFAULT_IND,MISC_NUM_FILL6,MISC_NUM_FILL7,MISC_NUM_FILL8,PAY_PROCESS_TIME,REG_REQUEST_DATE,ALT_ISSUE_DATE,CB_ENROLL_DATE,CB_STATUS,CB_COMMENT,FIRST_NAME,
RPP_PERMIT_NUMBER,IMAGE_IND,PENALTY_DATE1,PENALTY_DATE2,PENALTY_DATE3,PENALTY_DATE4,PENALTY_DATE5,DRIVEAWAY_FLAG,VEH_MODEL,VEH_YEAR_MONTH,HH_PLATE_EXP_DATE,COA_SOURCE,COMMENT_IND,OP_STATUS,ETL_STATUS_CD,ETL_SEQ_CD,TIMS_TIMESTAMP,REC_NO
 from(select a.*, rank() over 
(partition by tick_number order by tims_timestamp desc,etl_seq_cd desc) rec_no 
 from todays_catchup_tick_segment a WHERE etl_status_cd=15
 AND EXISTS (select 1 from todays_tick_list_stage2 t where a.tick_number=t.tick_number)
 ) WHERE rec_no=1;

COMMIT;


--****SAVE/REFERENCE purposes

truncate table todays_tm2_ticket_hist;

insert into todays_tm2_ticket_hist (ISN,TICKET_NUMBER,BATCH_DATE,BATCH_TIME,CLERK_ID,RECORD_TYPE,TRANS_CODE,PAYMENT_TYPE,PAY_AMOUNT,PAY_METHOD,PAY_PHONE_IND,PAY_FILL,PAY_PROCESS_DTE,PAY_BATCH_NUM,PAY_NOTICE_NUM,ACCOUNT_NUMBER,REFUND_CHECK_NO,REAPPLY_SOURCE,DISP_CODE,DISP_DTE,DISP_CLERK,DISP_PROCESS_DTE,HEARING_REDUCE_AMT,HEARING_FINE,HEARING_PEN1,HEARING_PEN2,HEARING_PEN3,
HEARING_PEN4,HEARING_PEN5,HEARING_OFFICER,HEARING_DATE,HEARING_TIME,HEARING_CLERK,HEARING_REQUIRED,HEARING_PLEA_CODE,DISPOSITION_BATCH,SUSPEND_CODE,SUSPEND_TIL_DATE,SUSPEND_PROCESS_DTE,NOTICE_TYPE,NOTICE_DATE,NOTICE_PROCESS_DTE,CORR_TYPE,ALPH_FIL_1,CORR_SENT_IND,ALPH_FIL_2,NUM_FIL_2,ALPH_FIL_3,NUM_FIL_3,LETTER_TYPE,N_A_FULL_NAME,N_A_ADDR_LINE1,N_A_ADDR_LINE2,N_A_CITY,
N_A_STATE,N_A_ZIP,ALPH_FIL_7,N_A_CHANGE_SOURCE,N_A_EMAIL_ADDRESS,N_A_TELEPHONE_NUMBER,ALPH_FIL_8,NUM_FIL_8,ALPH_FIL_9,NUM_FIL_9,HOLD_STATUS,HOLD_REQUEST_DATE,HOLD_PROCESS_DATE,PENALTY_NUMBER,PENALTY_ACTION,PENALTY_OLD_AMOUNT,PENALTY_NEW_AMOUNT,COMMENTS_DATA,OP_STATUS,ETL_STATUS_CD,ETL_SEQ_CD,TIMS_TIMESTAMP,SRC_ROWID)
select ts.ISN,ts.TICKET_NUMBER,ts.BATCH_DATE,ts.BATCH_TIME,ts.CLERK_ID,ts.RECORD_TYPE,ts.TRANS_CODE,ts.PAYMENT_TYPE,ts.PAY_AMOUNT,ts.PAY_METHOD,ts.PAY_PHONE_IND,ts.PAY_FILL,ts.PAY_PROCESS_DTE,ts.PAY_BATCH_NUM,ts.PAY_NOTICE_NUM,ts.ACCOUNT_NUMBER,ts.REFUND_CHECK_NO,ts.REAPPLY_SOURCE,ts.DISP_CODE,ts.DISP_DTE,ts.DISP_CLERK,ts.DISP_PROCESS_DTE,ts.HEARING_REDUCE_AMT,ts.HEARING_FINE,ts.HEARING_PEN1,ts.HEARING_PEN2,ts.HEARING_PEN3,
ts.HEARING_PEN4,ts.HEARING_PEN5,ts.HEARING_OFFICER,ts.HEARING_DATE,ts.HEARING_TIME,ts.HEARING_CLERK,ts.HEARING_REQUIRED,ts.HEARING_PLEA_CODE,ts.DISPOSITION_BATCH,ts.SUSPEND_CODE,ts.SUSPEND_TIL_DATE,ts.SUSPEND_PROCESS_DTE,ts.NOTICE_TYPE,ts.NOTICE_DATE,ts.NOTICE_PROCESS_DTE,ts.CORR_TYPE,ts.ALPH_FIL_1,ts.CORR_SENT_IND,ts.ALPH_FIL_2,ts.NUM_FIL_2,ts.ALPH_FIL_3,ts.NUM_FIL_3,ts.LETTER_TYPE,ts.N_A_FULL_NAME,ts.N_A_ADDR_LINE1,ts.N_A_ADDR_LINE2,ts.N_A_CITY,
ts.N_A_STATE,ts.N_A_ZIP,ts.ALPH_FIL_7,ts.N_A_CHANGE_SOURCE,ts.N_A_EMAIL_ADDRESS,ts.N_A_TELEPHONE_NUMBER,ts.ALPH_FIL_8,ts.NUM_FIL_8,ts.ALPH_FIL_9,ts.NUM_FIL_9,ts.HOLD_STATUS,ts.HOLD_REQUEST_DATE,ts.HOLD_PROCESS_DATE,ts.PENALTY_NUMBER,ts.PENALTY_ACTION,ts.PENALTY_OLD_AMOUNT,ts.PENALTY_NEW_AMOUNT,ts.COMMENTS_DATA,ts.OP_STATUS,ts.ETL_STATUS_CD,ts.ETL_SEQ_CD,ts.TIMS_TIMESTAMP,rowid as src_rowid
from stg_columbus_dtl.TM2_TICKET_HISTORY@stg_dblink ts
where ts.etl_status_cd=15 AND ts.op_status IN ('INSERT','UPDATE','SQL COMPUPDATE')
    AND tims_timestamp >= (select last_run_date from cfg_batch_run)
   AND tims_timestamp < (select last_run_date + days_to_run from cfg_batch_run);


commit;

--****** RP process start here ******

truncate table HOLD_RDS_RP_TBL reuse storage;
truncate table stg_rds_rp_tbl;

insert into HOLD_RDS_RP_TBL
SELECT    --   L# 1
      S.SUMM_ENTITY_NUMBER RP_ENTITY_ID,
      S.SUMM_TICKET_TYPE RP_TICKET_TYPE,
      SUBSTR(S.SUMM_STATE_DRIVER_LIC,1,2) rp_lic_state,
      S.SUMM_STATE_DRIVER_LIC RP_DRIVER_LICENSE,
      S.SUMM_DRIVER_LIC_CLASS RP_DRIVER_LIC_CLASS,
    --   L# 2
      SUBSTR(S.summ_state_plate,1,2) RP_PLATE_STATE,
      SUBSTR(S.summ_state_plate,3,7) RP_PLATE,
      S.summ_plate_type RP_PLATE_TYPE,
      CASE
        WHEN (9999999         - S.SUMM_EFF_DTE_INVERSE) < 1990001 or 
        	S.SUMM_EFF_DTE_INVERSE < 1990001 or S.SUMM_EFF_DTE_INVERSE = 0 or S.SUMM_EFF_DTE_INVERSE = 9999999
        THEN NULL
        WHEN (9999999         - S.SUMM_EFF_DTE_INVERSE) = 9999999
        THEN NULL
        WHEN (9999999        - S.SUMM_EFF_DTE_INVERSE) >= 1990001
        THEN TO_DATE(9999999 - S.SUMM_EFF_DTE_INVERSE,'YYYYDDD')
        WHEN S.SUMM_EFF_DTE_INVERSE = 9999999 or S.SUMM_EFF_DTE_INVERSE = 0 or S.SUMM_EFF_DTE_INVERSE IS NULL
        THEN NULL
        ELSE TO_DATE(S.SUMM_EFF_DTE_INVERSE,'YYYYDDD')
        --ELSE TO_DATE(1990001,'YYYYDDD')
      END RP_EFF_DATE,
      S.SUMM_EFF_DATE_SRCE RP_EFF_DATE_SOURCE,
      CASE
        WHEN S.SUMM_PLATE_EXPIRE_DTE < 1990001
        THEN NULL
        --ELSE TO_DATE(9999999 - S.SUMM_PLATE_EXPIRE_DTE,'YYYYDDD')
        ELSE TO_DATE(S.SUMM_PLATE_EXPIRE_DTE,'YYYYDDD')
      END RP_PLATE_EXPIRE_DATE, --*SUMM_PLATE_EXPIRE_DTE,
  --     L# 3
      S.SUMM_LAST_NAME_F RP_LAST_NAME,
      CASE
        WHEN NVL(S.SUMM_MULT_TERM_DATE,0) < 1990001
        THEN NULL
        ELSE TO_DATE(S.SUMM_MULT_TERM_DATE,'YYYYDDD')
      END RP_MULT_TERM_DATE, --SUMM_MULT_TERM_DATE
      S.SUMM_MULT_OWNER_NO RP_MULT_OWNER_NO,
      S.SUMM_IPP_NUMBER RP_IPP_NO,
      S.SUMM_RPP_IND RP_RPP_IND,
      S.SUMM_AGENCY_CODE RP_AGENCY_CODE,
   --    L# 4
      S.SUMM_TOTAL_INTEREST_DUE RP_TOTAL_INTEREST_DUE,
      CASE
        WHEN S.SUMM_INTEREST_CALC_DATE < 1990001
        THEN NULL
        --ELSE TO_DATE(9999999 - S.SUMM_INTEREST_CALC_DATE,'YYYYDDD')
        ELSE TO_DATE(S.SUMM_INTEREST_CALC_DATE,'YYYYDDD')
      END RP_INTEREST_CALC_DATE, --SUMM_INTEREST_CALC_DATE
      S.SUMM_SCOFLAW_DEF_IND RP_SCOFLAW_DEF_IND,
   --    L# 5
      S.SUMM_NAME RP_NAME,
      S.SUMM_ADDRESS_LINE_1 RP_ADDRESS_LINE_1,
      S.SUMM_ADDRESS_LINE_2 RP_ADDRESS_LINE_2,
      S.summ_country RP_COUNTRY,
  --     L# 6
      --S.summ_country RP_COUNTY, by Bhavtosh Not round on table as county
      S.SUMM_CITY RP_CITY,
      S.SUMM_STATE SUMM_STATE2,
      S.SUMM_ZIP_CODE RP_ZIP_CODE,
      S.SUMM_SEX RP_SEX,
      S.SUMM_EYE_CODE RP_EYE_CODE,
   --    L# 7
      S.SUMM_HEIGHT RP_HEIGHT,
      S.SUMM_WEIGHT RP_WEIGHT,
      S.SUMM_RACE RP_RACE,
      CASE
        WHEN S.SUMM_DATE_OF_BIRTH < 1990001
        THEN NULL
        ELSE TO_DATE(S.SUMM_DATE_OF_BIRTH,'YYYYDDD')
      END RP_DATE_OF_BIRTH, -- SUMM_DATE_OF_BIRTH,
      CASE
        WHEN S.SUMM_REQUEST_DATE < 1990001
        THEN NULL
        ELSE TO_DATE( S.SUMM_REQUEST_DATE,'YYYYDDD')
      END RP_DMV_REQUEST_DATE, --SUMM_REQUEST_DATE,
      CASE
        WHEN S.SUMM_CONFIRM_DATE < 1990001
        THEN NULL
        ELSE TO_DATE( S.SUMM_CONFIRM_DATE,'YYYYDDD')
      END RP_DMV_CONFIRM_DATE, -- SUMM_CONFIRM_DATE,
   --    L# 8
      S.SUMM_ADDRESS_STATUS RP_ADDRESS_STATUS,
      S.SUMM_VIN_NUMBER RP_VIN_NUMBER,
      S.SUMM_HOLD_STATUS RP_HOLD_STATUS,
      CASE
        WHEN S.SUMM_HOLD_DATE < 1990001
        THEN NULL
        --ELSE TO_DATE(9999999 - S.SUMM_HOLD_DATE,'YYYYDDD')
        ELSE TO_DATE(S.SUMM_HOLD_DATE,'YYYYDDD')
      END RP_HOLD_DATE, -- SUMM_HOLD_DATE
      CASE
        WHEN S.SUMM_REG_PROCESS_DATE < 1990001
        THEN NULL
        ELSE TO_DATE(S.SUMM_REG_PROCESS_DATE,'YYYYDDD')
      END RP_DMV_PROCESS_DATE, -- SUMM_REG_PROCESS_DATE,
   --    L# 9
      S.SUMM_SWAP_STATUS RP_SWAP_STATUS,
      CASE
        WHEN S.SUMM_SWAP_DATE < 1990001
        THEN NULL
        --ELSE TO_DATE(9999999 - S.SUMM_SWAP_DATE,'YYYYDDD')
        ELSE TO_DATE(S.SUMM_SWAP_DATE,'YYYYDDD')
      END RP_SWAP_DATE, -- SUMM_SWAP_DATE,
      S.SUMM_NIXIE_STATUS RP_NIXIE_STATUS,
      CASE
        WHEN S.SUMM_NIXIE_DATE < 1990001
        THEN NULL
        ELSE TO_DATE(S.SUMM_NIXIE_DATE,'YYYYDDD')
      END RP_NIXIE_DATE, -- SUMM_NIXIE_DATE,
      CASE
        WHEN S.SUMM_LAST_SEIZ_DATE < 1990001 or S.SUMM_LAST_SEIZ_DATE = 0 or S.SUMM_LAST_SEIZ_DATE = 9999999
        THEN NULL
        --ELSE TO_DATE(9999999 - S.SUMM_LAST_SEIZ_DATE,'YYYYDDD')
        ELSE TO_DATE(S.SUMM_LAST_SEIZ_DATE,'YYYYDDD')
      END RP_LAST_SEIZ_DATE, -- SUMM_LAST_SEIZ_DATE,
      S.SUMM_SEIZ_STATUS RP_SEIZ_STATUS,
      CASE
        WHEN S.SUMM_SEIZ_STAT_DATE < 1990001 or S.SUMM_SEIZ_STAT_DATE = 0 or S.SUMM_SEIZ_STAT_DATE = 9999999
        THEN NULL
        --ELSE TO_DATE(9999999 - S.SUMM_SEIZ_STAT_DATE,'YYYYDDD')
        ELSE TO_DATE(S.SUMM_SEIZ_STAT_DATE,'YYYYDDD')
      END RP_SEIZ_STAT_DATE, -- SUMM_SEIZ_STAT_DATE,
 --      L# 10
      S.SUMM_EXCLUDE_IND RP_EXCLUDE_IND,
      CASE
        WHEN S.SUMM_EXCLUDE_DATE < 1990001 or S.SUMM_EXCLUDE_DATE = 0 or S.SUMM_EXCLUDE_DATE = 9999999
        THEN NULL
        ELSE TO_DATE(S.SUMM_EXCLUDE_DATE,'YYYYDDD')
      END RP_EXCLUDE_DATE, -- SUMM_EXCLUDE_DATE,
      S.SUMM_EXCLUDE_TIME RP_EXCLUDE_TIME,
      S.SUMM_EXCLUDE_AGENCY RP_EXCLUDE_AGENCY,
      S.summ_PHONE_STATUS RP_PHONE_STATUS,
      CASE
        WHEN S.SUMM_PHONE_STATUS_DATE < 1990001 or S.SUMM_PHONE_STATUS_DATE = 0 or S.SUMM_PHONE_STATUS_DATE = 9999999
        THEN NULL
        --ELSE TO_DATE(9999999 - S.SUMM_PHONE_STATUS_DATE,'YYYYDDD')
        ELSE TO_DATE(S.SUMM_PHONE_STATUS_DATE,'YYYYDDD')
      END RP_PHONE_STATUS_DATE, -- summ_PHONE_STATUS_DATE,
    --   L# 11
      S.summ_PHONE_COMMENTS RP_PHONE_COMMENTS,
      S.SUMM_TIME_PAY_IND RP_TIME_PAY_IND,
      S.SUMM_ALT_NAME_IND RP_ALT_NAME_IND,
      S.SUMM_COMBINE_IND RP_COMBINE_IND,
      S.SUMM_CORPORATE_NAME_IND RP_CORPORATE_NAME_IND,
      S.SUMM_HOLD_REASON RP_DMV_HOLD_REASON,
  --     L# 12
      S.SUMM_IPP_INELIG_IND RP_IPP_INELIG_IND,
      S.SUMM_BAD_CHECK_IND RP_BAD_CHECK_IND,
      S.SUMM_NCOA_REQ_IND RP_NCOA_REQ_IND,
      S.SUMM_SSN RP_SSN,
      CASE
        WHEN S.SUMM_CB_ENROLL_DATE < 1990001 or S.SUMM_CB_ENROLL_DATE = 0 or S.SUMM_CB_ENROLL_DATE = 9999999
        THEN NULL
        --ELSE TO_DATE(9999999 - S.SUMM_CB_ENROLL_DATE,'YYYYDDD')
        ELSE TO_DATE(S.SUMM_CB_ENROLL_DATE,'YYYYDDD')
      END RP_CREDIT_BUR_ENROLL_DATE, -- SUMM_CB_ENROLL_DATE,
      S.SUMM_CB_STATUS RP_CREDIT_BUR_STATUS,
     --  L# 13
      CASE
        WHEN S.SUMM_CB_STATUS_DATE < 1990001 or S.SUMM_CB_STATUS_DATE = 0 or S.SUMM_CB_STATUS_DATE = 9999999
        THEN NULL
        --ELSE TO_DATE(9999999 - S.SUMM_CB_STATUS_DATE,'YYYYDDD')
          ELSE TO_DATE(S.SUMM_CB_STATUS_DATE,'YYYYDDD')
      END RP_CREDIT_BUR_STATUS_DATE, -- SUMM_CB_STATUS_DATE,
      S.SUMM_CB_AMOUNT_DUE RP_CREDIT_BUR_AMOUNT_DUE,
      S.SUMM_CB_COUNT RP_CREDIT_BUR_COUNT,
      S.SUMM_CB_ACCOUNT RP_CREDIT_BUR_ACCOUNT,
   --    L# 14
      s.TIMS_TIMESTAMP,  
      SYSTIMESTAMP RP_RDS_DATE_TIME,
      S.SUMM_FIRST_NAME RP_FIRST_NAME,
      CASE
        WHEN 9999999        - S.SUMM_LAST_ISSUE_DATE_INV < 1990001 or 
        	S.SUMM_LAST_ISSUE_DATE_INV < 1990001 or S.SUMM_LAST_ISSUE_DATE_INV = 0 or
        	S.SUMM_LAST_ISSUE_DATE_INV = 9999999
        THEN NULL
        WHEN 9999999        - S.SUMM_LAST_ISSUE_DATE_INV = 9999999
        THEN NULL
        WHEN (9999999        - S.SUMM_LAST_ISSUE_DATE_INV) >= 1990001
        THEN TO_DATE(9999999 - S.SUMM_LAST_ISSUE_DATE_INV,'YYYYDDD')
        WHEN S.SUMM_LAST_ISSUE_DATE_INV =  9999999
        THEN NULL
        ELSE TO_DATE(S.SUMM_LAST_ISSUE_DATE_INV,'YYYYDDD')
      END RP_LAST_ISSUE_DATE,
      S.SUMM_ADDRESS_USERID RP_ADDRESS_USERID,
     --  L# 15
      CASE
        WHEN S.SUMM_MULTI_ENROLL_PROCDTE < 1990001 or S.SUMM_MULTI_ENROLL_PROCDTE = 0 or S.SUMM_MULTI_ENROLL_PROCDTE = 9999999
        THEN NULL
        --ELSE TO_DATE(9999999 - S.SUMM_MULTI_ENROLL_PROCDTE,'YYYYDDD')
        ELSE TO_DATE(S.SUMM_MULTI_ENROLL_PROCDTE,'YYYYDDD')
      END RP_MULTI_ENROLL_PROCDTE, -- SUMM_MULTI_ENROLL_PROCDTE,
      CASE
        WHEN S.SUMM_MULTI_TERM_PROCDTE < 1990001 or S.SUMM_MULTI_TERM_PROCDTE = 0 or S.SUMM_MULTI_TERM_PROCDTE = 9999999
        THEN NULL
        --ELSE TO_DATE(9999999 - S.SUMM_MULTI_TERM_PROCDTE,'YYYYDDD')
        ELSE TO_DATE(S.SUMM_MULTI_TERM_PROCDTE,'YYYYDDD')
      END RP_MULTI_TERM_PROCDTE, -- SUMM_MULTI_TERM_PROCDTE,
      S.SUMM_IPP_NUMBER SUMM_IPP_NUMBER2,
      S.SUMM_IPP_TICK_COUNT RP_IPP_TICK_COUNT,
      S.SUMM_IPP_AMT_DUE RP_IPP_AMT_DUE,
   --    L# 16
      S.SUMM_NIXIE_TICK_CNT RP_NIXIE_TICK_CNT,
      CASE
        WHEN S.SUMM_IPP_DATE < 1990001 or S.SUMM_IPP_DATE = 0 or S.SUMM_IPP_DATE = 9999999
        THEN NULL
        --ELSE TO_DATE(9999999 - S.SUMM_IPP_DATE,'YYYYDDD')
        ELSE TO_DATE(S.SUMM_IPP_DATE,'YYYYDDD')
      END RP_IPP_DATE,
      TO_NUMBER(TRIM(S.SUMM_COMMENT_IND)) RP_COMMENT_IND,
      CASE
        WHEN S.SUMM_OWNERSHIP_DATE < 1990001 or S.SUMM_OWNERSHIP_DATE = 0 or S.SUMM_OWNERSHIP_DATE = 9999999
        THEN NULL
        --ELSE TO_DATE(9999999 - S.SUMM_OWNERSHIP_DATE,'YYYYDDD')
        ELSE TO_DATE(S.SUMM_OWNERSHIP_DATE,'YYYYDDD')
      END RP_OWNERSHIP_DATE, -- SUMM_OWNERSHIP_DATE,
      'TBD' RP_EMAIL_ADDRESS,
    --   L# 17
      S.SUMM_COMBINE_TYPE RP_COMBINE_TYPE,
      CASE
        WHEN S.SUMM_COMBINE_DATE < 1990001 or S.SUMM_COMBINE_DATE = 0 or S.SUMM_COMBINE_DATE = 9999999
        THEN NULL
        ELSE TO_DATE(S.SUMM_COMBINE_DATE,'YYYYDDD')
      END RP_COMBINE_DATE, --SUMM_COMBINE_DATE,
      S.SUMM_COMBINE_TIME RP_COMBINE_TIME,
      S.SUMM_COMBINE_USERID RP_COMBINE_USERID,
      S.SUMM_TICKET_COUNT RP_TICKET_COUNT,
      CASE
        WHEN S.SUMM_ASSIGN_DATE < 1990001 or S.SUMM_ASSIGN_DATE = 0 or S.SUMM_ASSIGN_DATE = 9999999
        THEN NULL
        --ELSE TO_DATE(9999999 - S.SUMM_ASSIGN_DATE,'YYYYDDD')
        ELSE TO_DATE(S.SUMM_ASSIGN_DATE,'YYYYDDD')
      END RP_ASSIGN_DATE, -- SUMM_ASSIGN_DATE
    --   L# 18
      S.SUMM_HOLD_TICK_CNT RP_HOLD_TICK_CNT,
      S.SUMM_HOLD_ELIG_CNT RP_HOLD_ELIG_CNT,
      S.SUMM_BOOTBL_TICK_CNT RP_BOOTBL_TICK_CNT,
      S.SUMM_SEIZ_ELIG_CNT RP_SEIZ_ELIG_CNT,
    --   L# 19
      S.SUMM_PLATE_SUB_TYPE RP_PLATE_SUB_TYPE,
      S.SUMM_IPP_STATUS RP_IPP_STATUS,
      'TBD' RP_TELEPHONE_NUMBER,
      S.summ_telephone_number RP_PHONE_NUMBER,
      RANK() OVER(PARTITION BY s.SUMM_ENTITY_NUMBER ORDER BY S.tims_timestamp DESC) rec_num
    FROM stg_tm2_ticket_summary s WHERE s.SUMM_ENTITY_NUMBER > '0' 
    and S.summ_home_ind='1' AND s.op_status IN ('INSERT','UPDATE','SQL COMPUPDATE');


COMMIT;

	
insert into stg_rds_rp_tbl
(
RP_ENTITY_ID, RP_TICKET_TYPE, RP_DRIVER_LIC_STATE, RP_DRIVER_LICENSE, RP_DRIVER_LIC_CLASS, RP_PLATE_STATE,
RP_PLATE, RP_PLATE_TYPE, RP_EFF_DATE, RP_EFF_DATE_SOURCE, RP_PLATE_EXPIRE_DATE, RP_LAST_NAME,
RP_MULT_TERM_DATE, RP_MULT_OWNER_NO, RP_IPP_NO, RP_RPP_IND, RP_AGENCY_CODE, RP_TOTAL_INTEREST_DUE,
RP_INTEREST_CALC_DATE, RP_SCOFLAW_DEF_IND, RP_NAME, RP_ADDRESS_LINE_1, RP_ADDRESS_LINE_2,
RP_COUNTRY, RP_CITY, RP_STATE, RP_ZIP_CODE, RP_SEX, RP_EYE_CODE, RP_HEIGHT, RP_WEIGHT, RP_RACE,
RP_DATE_OF_BIRTH, RP_DMV_REQUEST_DATE, RP_DMV_CONFIRM_DATE, RP_ADDRESS_STATUS, RP_VIN_NUMBER, RP_HOLD_STATUS, 
RP_HOLD_DATE, RP_DMV_PROCESS_DATE, RP_SWAP_STATUS, RP_SWAP_DATE, RP_NIXIE_STATUS, RP_NIXIE_DATE, 
RP_LAST_SEIZ_DATE, RP_SEIZ_STATUS, RP_SEIZ_STAT_DATE, RP_EXCLUDE_IND, RP_EXCLUDE_DATE, 
RP_EXCLUDE_TIME, RP_EXCLUDE_AGENCY, RP_PHONE_STATUS, RP_PHONE_STATUS_DATE,RP_PHONE_COMMENTS, 
RP_TIME_PAY_IND, RP_ALT_NAME_IND, RP_COMBINE_IND, RP_CORPORATE_NAME_IND,RP_DMV_HOLD_REASON, 
RP_IPP_INELIG_IND, RP_BAD_CHECK_IND, RP_NCOA_REQ_IND, RP_SSN,RP_CREDIT_BUR_ENROLL_DATE, RP_CREDIT_BUR_STATUS,
RP_CREDIT_BUR_STATUS_DATE, RP_CREDIT_BUR_AMOUNT_DUE,RP_CREDIT_BUR_COUNT, RP_CREDIT_BUR_ACCOUNT, 
RP_TIMS_DATE_TIME, RP_RDS_DATE_TIME, RP_FIRST_NAME,RP_LAST_ISSUE_DATE, RP_ADDRESS_USERID, 
RP_MULTI_ENROLL_PROCDTE, RP_MULTI_TERM_PROCDTE, RP_IPP_NUMBER,RP_IPP_TICK_COUNT, RP_IPP_AMT_DUE, 
RP_NIXIE_TICK_CNT, RP_IPP_DATE, RP_COMMENT_IND, RP_OWNERSHIP_DATE,RP_EMAIL_ADDRESS,
RP_COMBINE_TYPE, RP_COMBINE_DATE, RP_COMBINE_TIME, RP_COMBINE_USERID, RP_TICKET_COUNT,RP_ASSIGN_DATE, 
RP_HOLD_TICK_CNT, RP_HOLD_ELIG_CNT, RP_BOOTBL_TICK_CNT, RP_SEIZ_ELIG_CNT,RP_PLATE_SUB_TYPE, 
RP_IPP_STATUS, RP_PHONE_NUMBER, RP_TELEPHONE_NUMBER)
select
RP_ENTITY_ID, RP_TICKET_TYPE, RP_LIC_STATE, RP_DRIVER_LICENSE, RP_DRIVER_LIC_CLASS, RP_PLATE_STATE,
RP_PLATE, RP_PLATE_TYPE, RP_EFF_DATE, RP_EFF_DATE_SOURCE, RP_PLATE_EXPIRE_DATE, RP_LAST_NAME,
RP_MULT_TERM_DATE, RP_MULT_OWNER_NO, RP_IPP_NO, RP_RPP_IND, RP_AGENCY_CODE, RP_TOTAL_INTEREST_DUE,
RP_INTEREST_CALC_DATE, RP_SCOFLAW_DEF_IND, RP_NAME, RP_ADDRESS_LINE_1, RP_ADDRESS_LINE_2,
RP_COUNTRY, RP_CITY, SUMM_STATE2, RP_ZIP_CODE, RP_SEX, RP_EYE_CODE, RP_HEIGHT, RP_WEIGHT, RP_RACE,
RP_DATE_OF_BIRTH, RP_DMV_REQUEST_DATE, RP_DMV_CONFIRM_DATE, RP_ADDRESS_STATUS, RP_VIN_NUMBER, RP_HOLD_STATUS,
RP_HOLD_DATE, RP_DMV_PROCESS_DATE, RP_SWAP_STATUS, RP_SWAP_DATE, RP_NIXIE_STATUS, RP_NIXIE_DATE,
RP_LAST_SEIZ_DATE, RP_SEIZ_STATUS, RP_SEIZ_STAT_DATE, RP_EXCLUDE_IND, RP_EXCLUDE_DATE,
RP_EXCLUDE_TIME, RP_EXCLUDE_AGENCY, RP_PHONE_STATUS, RP_PHONE_STATUS_DATE, RP_PHONE_COMMENTS,
RP_TIME_PAY_IND, RP_ALT_NAME_IND, RP_COMBINE_IND, RP_CORPORATE_NAME_IND, RP_DMV_HOLD_REASON,
RP_IPP_INELIG_IND, RP_BAD_CHECK_IND, RP_NCOA_REQ_IND, RP_SSN, RP_CREDIT_BUR_ENROLL_DATE, RP_CREDIT_BUR_STATUS,
RP_CREDIT_BUR_STATUS_DATE, RP_CREDIT_BUR_AMOUNT_DUE, RP_CREDIT_BUR_COUNT, RP_CREDIT_BUR_ACCOUNT,
TIMS_TIMESTAMP, RP_RDS_DATE_TIME, RP_FIRST_NAME, RP_LAST_ISSUE_DATE, RP_ADDRESS_USERID,
RP_MULTI_ENROLL_PROCDTE, RP_MULTI_TERM_PROCDTE, SUMM_IPP_NUMBER2, RP_IPP_TICK_COUNT, RP_IPP_AMT_DUE,
RP_NIXIE_TICK_CNT, RP_IPP_DATE, RP_COMMENT_IND, RP_OWNERSHIP_DATE, RP_EMAIL_ADDRESS,
RP_COMBINE_TYPE, RP_COMBINE_DATE, RP_COMBINE_TIME, RP_COMBINE_USERID, RP_TICKET_COUNT, RP_ASSIGN_DATE,
RP_HOLD_TICK_CNT, RP_HOLD_ELIG_CNT, RP_BOOTBL_TICK_CNT, RP_SEIZ_ELIG_CNT, RP_PLATE_SUB_TYPE,
RP_IPP_STATUS, RP_TELEPHONE_NUMBER, RP_PHONE_NUMBER
from hold_rds_rp_tbl WHERE rec_num = 1;

COMMIT;

DELETE FROM RDS_RP_TBL D WHERE EXISTS
(SELECT 1 FROM stg_tm2_ticket_summary t WHERE D.RP_ENTITY_ID = T.SUMM_ENTITY_NUMBER);

INSERT INTO RDS_RP_TBL select * from stg_rds_rp_tbl;
    
COMMIT;


UPDATE stg_columbus_dtl.TM2_TICKET_SUMMARY@stg_dblink S
SET ETL_STATUS_CD = 20 WHERE ETL_STATUS_CD = 15;

COMMIT;

update WK_BATCH_TRACKER set end_time=systimestamp, run_status='Y' where STEP_NAME='RDS RP';
COMMIT;

EXIT;

